///@description Initialize
	
	super();
	
	#region Fields
	
///@public:

	///@type {Stack<LyricsTask>}
	lyricsTaskPipeline = createStack();
		
///@private:

	///@type {Surface}
	lyricsSurface = createSurface(global.guiWidth, global.guiHeight, true);

	///@type {String[]}
	lyrics = [];

	///@type {List<LyricRow>}
	// TODO Entity
	lyricsPipeline = createList();

	///@type {Number}
	textVerticalMargin = 128;
	
	///@type {Number}
	textHorizontalMargin = 96;
	
	///@type {Number}
	textHeight = 20;
	
	///@type {Boolean}
	enableLyricsRenderer = true;
	
	///@type {Number}
	lifespan = 0.0;
	
	///@type {number}
	lifespanTimer = 0.0;
	
	///@type {Number}
	duration = 0.0;
	
	///@type {Number}
	durationTimer = 0.0;
	
	///@type {GMColor[]}
	colors = [
		make_color_rgb(255, 255, 255),
		make_color_rgb(245, 245, 235),
		make_color_rgb(235, 215, 235),
		make_color_rgb(255, 205, 195),
		make_color_rgb(255, 255, 255),
	];
	
	///@type {Number}
	alpha = 0.0;

	#endregion
	
	lain01 = true;
	global.__lyrics = [
		"                                             ",
		"                                             ",
		"                                             ",
		"                                             ",
        "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
        "MMMMMMMMMMMMds+:--------:+sdNMMMMMMMMMMM",
        "                                             ",
        "MMMMMMMMms:-+sdNMMMMMMMMNdy+--omMMMMMMMM",
        "MMMMMMh:` /mMMMMMMMMMMMMMMMMm+ `-yMMMMMM",
        "MMMMd--hN``--sNMMMMMMMMMMNy:..`md:.hMMMM",
        "   MMM+`yMMMy hd+./hMMMMMMh/.+dd sMMMh`/MMM",
        "   MM:.mMMMMM:.NMMh/.+dd+./hMMM--MMMMMm--NM",
        "                                             ",
        "   M+`mMMMMMMN`+MMMMm-  .dMMMMo mMMMMMMN.:M",
        "    d yMMMMMMMMy dNy:.omNs--sNm oMMMMMMMMh h",
        "     /`MMMMMMMMMM.`.+dMMMMMMm+.``NMMMMMMMMM-:",
        "     .:MMMMMMMd+./`oMMMMMMMMMMs /.+dMMMMMMM/`",
        "      `.:MMMMmo.:yNMs dMMMMMMMMm`oMNy:.omMMMM/`",
        "      /`MNy:.omMMMMM--MMMMMMMM:.MMMMMNs--sNM.:",
        "         d -` :++++++++: /++++++/ :++++++++:  : h",
        "                                             ",
        "After losing a dear person, ",
        "    d yMMMMMMMMy dNy:.omNs--sNm oMMMMMMMMh h",
        "     /`MMMMMMMMMM.`.+dMMMMMMm+.``NMMMMMMMMM-:",
        "     .:MMMMMMMd+./`oMMMMMMMMMMs /.+dMMMMMMM/`",
        "Vain tried to capture her soul in a Cristamonium diamond. ",
        "What he doesn't know is that the diamond is not ",
        "a portal to the other side but to a far away galaxy. ",
        "                                             ",
        "                             /\\",
        "                         ___/__\\___",
        "                         `-/.  ,\\-'",
        "                          /,-''-,\\",
        "                         /'      `\\",
        "When he uses it, he accidentally transports ",
        "an alien princess to Earth. ",
        "   MMMMd--hMMMMMMMMM+`mN`/MMMMMMMMMh--hMMMM",
        "    MMMMMMh:.omMMMMMMN.:/`NMMMMMMms.:hMMMMMM",
        "     MMMMMMMMNs:./shmMMh  yMMNds/.:smMMMMMMMM",
        "But her mother, queen of an entire galaxy, sends ",
        "a brutal mercenary known as Burning Void to retrieve the princess. ",
        "After a battle on the higher orbit, Void and ",
        "   MMMMd--hMMMMMMMMM+`mN`/MMMMMMMMMh--hMMMM",
        "    MMMMMMh:.omMMMMMMN.:/`NMMMMMMms.:hMMMMMM",
        "                                             ",
        "                  /\\",
        "              ___/__\\___",
        "              `-/.  ,\\-'",
        "               /,-''-,\\",
        "              /'      `\\",
        "     MMMMMMMMNs:./shmMMh  yMMNds/.:smMMMMMMMM",
        "    MMMMMMMMMMMMdy+/---``---:+sdMMMMMMMMMMMM",
        "   ` MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
		"                                             ",
		"                                             ",
		"                                             ",
		"                                             ",
		"                                             ",
        "Vain get new paths to follow and the two galaxies are changed forever.",
        "                                             ",
        "    M+ yddddddddddd+ yddddy /dddddddddddy`/M",
        "    MM/.mMMMMMMMMMMM.-MMMM/.NMMMMMMMMMMm.:NM",
        "   MMMo`sMMMMMMMMMMd sMMy hMMMMMMMMMMy`+MMM",
        "   MMMMd--hMMMMMMMMM+`mN`/MMMMMMMMMh--hMMMM",
        "    MMMMMMh:.omMMMMMMN.:/`NMMMMMMms.:hMMMMMM",
        "     MMMMMMMMNs:./shmMMh  yMMNds/.:smMMMMMMMM",
        "    MMMMMMMMMMMMdy+/---``---:+sdMMMMMMMMMMMM",
        "   ` MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM",
		"                                             ",
		"                                             ","                                             ",
		"                                             ",
		"                                             ",
		"                                             ",
        " - Chelariu Cristian",
        "                                             ",
        "",
        "             ",

        "                        ",
        "           /\\",
        "       ___/__\\___",
        "       `-/.  ,\\-'",
        "        /,-''-,\\",
        "       /'      `\\",
        "      ",
        "",
			"",
		"           `#@@@@@@:",
		"         @@@,     `#@@.`",
		"       @@.           `@@",
		"     .@;               .@:",
		"    `@+@` `            @@@+",
		"   .@  @@'           ,@'. @'",
		"   @   @ '@         @# @   @.",
		"  @`   +. `@       @,  @    @",
		" :@     @   @#   '#   ;,    +@",
		" @      @    ,@ @+    @      @",
		"`@      #.    `@`     @      '#",
		"@        @   +@ #@   :;       @",
		"@        @  @'   .@  @        @",
		"@        #`@     ` @'#        @`",
		"@         @         #@        ':",
		"@       @.@         @`@.      :'",
		"#   ` ;#  @`        @  @#     :+",
		"@    @+`   @       ,;   :@    ;;",
		"@  `@      @       @      @:  @.",
		"@ #@       @       @       #@ @",
		"@@@@@@@@@@@@@@@@@@,'@@@@ @@@@@@@",
		",#                @          :#",
		" @          @     @          @",
		" ;+         `+   `'         ,@",
		"  @          @   @          @",
		"   @         @   @         @:",
		"   ,@        ,+ `'        #@",
		"    ,@        @ @        @#",
		"     .@``     @ @       @+",
		"       @@     ,'+     #@`",
		"        `@@:   @   ,@@:",
		"           :@@@@@@@+",
		"",
		"",
		"            /\\ ",
		"           /  \\",
		" _________/____\\_________",
		" '-.     /      \\     ,-'",
		"    '-, /        \\ ,-'",
		"       /-.      ,-\\",
		"      /   '-,.-'   \\",
		"     /    ,-''-.    \\",
		"    /  ,-'      '-.  \\",
		"   /,-'            '-.\\",
		"",
		"",
		"           /\\",
		"          /  \\",
		"_________/____\\_________",
		"`-._    /      \\    _,-'",
		"    `-./        \\.-'",
		"      / `-.  ,-' \\",
		"     /  _,-'`-._  \\",
		"    /,-'        `-.\\",
		"   /'              `\\",
		"",
		"",
		"",
		"         /\\",
		" _______/__\\_______",
		" `-.   /    \\   ,-'",
		"    `-/      \\-'",
		"     / `-.,-' \\",
		"    /  ,-''-.  \\",
		"   /,-'      `-.\\",
		"   '            `",
		"",
		"",
		"       /\\",
		" _____/__\\_____",
		" `-. /    \\ ,-'",
		"    /-.  .-\\",
		"   /  ,`'.  \\",
		"  /,-'    '-.\\",
		"  '          `",
		"",
		"",
		"      /\\",
		" =---/--\\---=",
		"  `-/    \\-'",
		"   / `,.' \\",
		"  /,-'  '-.\\",
		"  '        `",
		"",
		"",
		"     /\\",
		" ___/__\\___",
		" `-/.  ,\\-'",
		"  /,-''-,\\",
		" /'      `\\",
		"",
		"",
		"    /\\   ",
		"-.-/--\\-,- ",
		"  /-.,-\\",
		" /,-''-.\\",
		"",
		"",
		"   /\\ ",
		"=:/--\\:=",
		" /,'',\\",
		"",
		"",
		"__/\\__",
		" /;:\\",
		"",
		"@@ -853,7 +879,20 @@",
		" 			        {",
		" 			            keyboardMapping: [ \"X\", \"8\" ],",
		" 			            pressed: function () {",
		"-",
		"+							",
		"+							try {",
		"+								var eventsRecorder = getGameController().midiMatrixController.eventsRecorder;",
		"+								if isStruct(eventsRecorder.getCurrentRecording(eventsRecorder)) {",
		"+								",
		"+									eventsRecorder.stopRecording(eventsRecorder);	",
		"+								} else {",
		"+								",
		"+									eventsRecorder.startRecording(eventsRecorder);	",
		"+								}",
		"+							} catch(exception) {",
		"+								logger(exception.message, LogType.INFO);",
		"+								printStackTrace();",
		"+							}",
		" 			            }",
		" 			        }",
		" 			    ),",
		"@@ -863,6 +902,16 @@",
		" 			            keyboardMapping: [ \"C\", \"8\" ],",
		" 			            pressed: function () {",
		" ",
		"+							try {",
		"+								var eventsRecorder = getGameController().midiMatrixController.eventsRecorder;",
		"+								var text = Core.File.read({ withDialog: true });",
		"+								var eventsRecording = eventsRecorder.parseRecording(eventsRecorder, text);",
		"+								var eventsPlayer = getGameController().midiMatrixController.eventsPlayer;",
		"+								eventsPlayer.play(eventsPlayer, eventsRecording);",
		"+							} catch(exception) {",
		"+								logger(exception.message, LogType.INFO);",
		"+								printStackTrace();",
		"+							}",
		" 			            }",
		" 			        }",
		" 			    ),",
		"@@ -872,6 +921,11 @@",
		" 			            keyboardMapping: [ \"V\", \"8\" ],",
		" 			            pressed: function () {",
		" ",
		"+							var shrooms = getInstanceVariable(getShroomManager(), \"shrooms\");",
		"+							if (isDataStructure(shrooms, List)) {",
		"+							",
		"+								clearList(shrooms);",
		"+							}",
		" 			            }",
		" 			        }",
		" 			    )",
		"diff --git a/yyp/objects/GridRenderer/Create_0.gml b/yyp/objects/GridRenderer/Create_0.gml",
		"index 9810de9..a0d5af7 100644",
		"--- a/yyp/objects/GridRenderer/Create_0.gml",
		"+++ b/yyp/objects/GridRenderer/Create_0.gml",
		"@@ -303,6 +303,24 @@",
		" 	",
		" 	#region Methods",
		" 	",
		"+	blendModes = [",
		"+	    bm_zero,",
		"+	    bm_one,",
		"+	    bm_src_colour,",
		"+	    bm_inv_src_colour,",
		"+	    bm_src_alpha,",
		"+	    bm_inv_src_alpha,",
		"+	    bm_dest_alpha,",
		"+	    bm_inv_dest_alpha,",
		"+	    bm_dest_colour,",
		"+	    bm_inv_dest_colour,",
		"+	    bm_src_alpha_sat,",
		"+	]",
		"+",
		"+	firstBlendPointer = 1;",
		"+	secondBlendPointer = 5;",
		"+	blendModesLength = getArrayLength(blendModes);",
		"+	",
		" 	gridEventPipelineDispatcher = method(this, function(pipeline) {",
		" 		",
		" 		for (var gridEvent = getPipelineFirstElement(pipeline);",
		"@@ -575,6 +593,24 @@",
		" 		",
		" 			if (enableGridElementsRendering) {",
		" 			",
		"+				if (keyboard_check_pressed(ord(\"I\"))) {",
		"+					firstBlendPointer = clamp(firstBlendPointer + 1, 0, blendModesLength - 1);",
		"+					logger(\"firstBlendPointer {0}\", LogType.DEBUG, firstBlendPointer);",
		"+				}",
		"+				if (keyboard_check_pressed(ord(\"K\"))) {",
		"+					firstBlendPointer = clamp(firstBlendPointer- 1, 0, blendModesLength - 1);",
		"+					logger(\"firstBlendPointer {0}\", LogType.DEBUG, firstBlendPointer);",
		"+				}",
		"+					",
		"+				if (keyboard_check_pressed(ord(\"O\"))) {",
		"+					secondBlendPointer = clamp(secondBlendPointer + 1, 0, blendModesLength - 1);",
		"+					logger(\"secondBlendPointer {0}\", LogType.DEBUG, secondBlendPointer);",
		"+				}",
		"+				if (keyboard_check_pressed(ord(\"L\"))) {",
		"+					secondBlendPointer = clamp(secondBlendPointer - 1, 0, blendModesLength - 1);",
		"+					logger(\"secondBlendPointer {0}\", LogType.DEBUG, secondBlendPointer);",
		"+				}",
		"+				gpu_set_blendmode_ext(blendModes[firstBlendPointer], blendModes[secondBlendPointer]);",
		" 				var dimension = max(viewWidth, viewHeight);",
		" 				var gridElementPipelineSize = getPriorityQueueSize(gridElementPipeline);",
		" 				for (var index = 0; index < gridElementPipelineSize; index++) {",
		"@@ -710,6 +746,7 @@",
		" 					}",
		" 					#endregion",
		" 				}",
		"+				gpu_set_blendmode(bm_normal);",
		" 			}",
		" 			",
		" 			#endregion",
		"diff --git a/yyp/objects/LyricsRenderer/Create_0.gml b/yyp/objects/LyricsRenderer/Create_0.gml",
		"index 85dd04a..5c86868 100644",
		"--- a/yyp/objects/LyricsRenderer/Create_0.gml",
		"+++ b/yyp/objects/LyricsRenderer/Create_0.gml",
		"@@ -59,8 +59,9 @@",
		" ",
		" 	#endregion",
		" 	",
		"-	lain01 = false;",
		"+	lain01 = true;",
		" 	global.__lyrics = [	",
		"+/*",
		" \"                                                          \",",
		" \"                                                          \",",
		" \"            goodluck! cross                             \",",
		"@@ -559,6 +560,8 @@",
		" \"\",",
		" \"\",",
		" \"ATTENTION CITIZEN! 市民请注意!\",",
		"+*/",
		"+/*",
		" \"流れてく 時の中ででも\",",
		" \"気だるさが ほらグルグル廻って\",",
		" \"私から 離れる心も\",",
		"@@ -827,4 +830,5 @@",
		" \"\",",
		" \"\",",
		" \"\"",
		"+*/",
		" ]",
		"diff --git a/yyp/scripts/MidiMatrixController/MidiMatrixController.gml b/yyp/scripts/MidiMatrixController/MidiMatrixController.gml",
		"index 831b326..fe9387d 100644",
		"--- a/yyp/scripts/MidiMatrixController/MidiMatrixController.gml",
		"+++ b/yyp/scripts/MidiMatrixController/MidiMatrixController.gml",
		"@@ -6,20 +6,68 @@ function createMidiMatrixController(config) {",
		" 	return {",
		" 		surface: createSurface(1, 1, true),",
		" 		keymapConfig: config,",
		"+		eventsPlayer: createEventsPlayer(),",
		"+		eventsRecorder: createEventsRecorder(),",
		"+		",
		"+		__checkButtonKeyboardMapping: function(button) {",
		"+			",
		"+			var result = false;",
		"+			var keyboardMapping = getStructVariable(button, \"keyboardMapping\");",
		"+			if (isArray(keyboardMapping)) {",
		"+						",
		"+				var length = getArrayLength(keyboardMapping);",
		"+				for (var index = 0; index < length; index++) {",
		"+				",
		"+					var keyboardKey = keyboardMapping[index];",
		"+					var keyCheckResult = keyboard_check_pressed(ord(keyboardKey));",
		"+					if (keyCheckResult) {",
		"+						",
		"+						result = (index == 0) ? true : (keyCheckResult && result) == true;",
		"+					} else {",
		"+					",
		"+						result = false;",
		"+						break;",
		"+					}",
		"+				}",
		"+			}",
		"+			",
		"+			return result;",
		"+		},",
		" 		",
		" 		update: function(midiController) {",
		" 			",
		"+			midiController.eventsRecorder.update(midiController.eventsRecorder);",
		"+			midiController.eventsPlayer.update(midiController.eventsPlayer, midiController.keymapConfig);",
		" 			",
		" 			for (var key = mapFirst(midiController.keymapConfig);",
		" 				 iteratorFinish(key);",
		"-				 key = mapNext(keymapConfig, key)) {",
		"+				 key = mapNext(midiController.keymapConfig, key)) {",
		" 					 ",
		"-				var button = keymapConfig[? key];	 ",
		"+				var button = midiController.keymapConfig[? key];	 ",
		" 				if ((midiController.__checkButtonKeyboardMapping(button)) ",
		" 					&& (isOptionalPresent(getStructVariable(button, \"pressed\")))) {",
		" 					",
		" 					// asker imoiskar",
		" 					button.pressed(button, key);",
		"+					",
		"+					var currentRecording = midiController.eventsRecorder.getCurrentRecording(midiController.eventsRecorder);",
		"+					if (isStruct(currentRecording)) {",
		"+						",
		"+						if ((key != \"5x7\") &&",
		"+							(key != \"6x7\")) {",
		"+						",
		"+							midiController.eventsRecorder.registerEvent(",
		"+								midiController.eventsRecorder, { ",
		"+									name: \"MidiControllerButtonEvent\", ",
		"+									data: { ",
		"+										key: key,",
		"+										timestamp: currentRecording.timer,",
		"+										log: Core.Collections._Queue.getTail(getLoggerQueue())",
		"+									}",
		"+								}	",
		"+							);",
		"+						}",
		"+					}",
		" 				}",
		" 			}",
		" 		},",
		"@@ -83,31 +131,189 @@ function createMidiMatrixController(config) {",
		" 		cleanUp: function(midiController) {",
		" 		",
		" 			destroyMap(midiController.keymapConfig);",
		"+		}",
		"+	}",
		"+}",
		"+",
		"+function createEventsPlayer() {",
		"+",
		"+	return {",
		"+	",
		"+		recording: null,",
		"+		",
		"+		play: function(eventsPlayer, eventsRecording) {",
		"+		",
		"+			try {",
		"+				eventsPlayer.recording = {",
		"+					timer: 0.0,",
		"+					duration: eventsRecording.timer,",
		"+					events: eventsRecording.events,",
		"+					eventPointer: 0",
		"+				}",
		"+			} catch (exception) {",
		"+				logger(exception.message, LogType.ERROR);",
		"+				printStackTrace();",
		"+			}",
		" 		},",
		"+		update: function(eventsPlayer, keymapConfig) {",
		"+					",
		"+			var recording = eventsPlayer.recording;",
		"+			if (isStruct(recording)) {",
		"+				",
		"+				//print(\"PLAYING\");",
		"+				recording.timer = incrementTimer(recording.timer, recording.duration);",
		"+				if (timerFinished(recording.timer)) {",
		"+					",
		"+					eventsPlayer.recording = null;	",
		"+					return;",
		"+				} else {",
		"+					var size = Core.Collections._Array.size(recording.events)",
		"+					if (size > 0) && (size > recording.eventPointer) {",
		"+				",
		"+						var event = recording.events[recording.eventPointer];",
		"+						if (recording.timer >= event.data.timestamp) {",
		"+						",
		"+							try {",
		"+								recording.eventPointer++",
		"+								var key = event.data.key;",
		"+								var button = Core.Collections._Map.get(keymapConfig, key);",
		"+								button.pressed(button, key);",
		"+							} catch (exception) {",
		"+								logger(exception.message, LogType.ERROR);",
		"+								printStackTrace();",
		"+							}",
		"+						}",
		"+					}",
		"+				}",
		"+			}",
		"+		}",
		"+	}",
		"+}",
		"+",
		"+function createEventsRecorder() {",
		"+",
		"+	return {",
		"+		state: createEmptyOptional(),",
		" 		",
		"-		__checkButtonKeyboardMapping: function(button) {",
		"+		startRecording: function(eventsRecorder) {",
		" 			",
		"-			var result = false;",
		"-			var keyboardMapping = getStructVariable(button, \"keyboardMapping\");",
		"-			if (isArray(keyboardMapping)) {",
		"-						",
		"-				var length = getArrayLength(keyboardMapping);",
		"-				for (var index = 0; index < length; index++) {",
		"+			var currentRecording = {",
		"+				timer: 0.0,",
		"+				events: [],",
		"+				audio: {",
		"+					name: getAssetName(asset_ost_boa_duvet_virtual_self, AssetSound), ///@todo mockup",
		"+					trackPosition: random(100) ///@todo mockup",
		"+				},",
		"+				layout: {",
		"+					name: \"novation-launchpad\", ///@todo mockup",
		"+					page: 0 ///@todo mockup",
		"+				}",
		"+			};",
		"+			eventsRecorder.setCurrentRecording(eventsRecorder, currentRecording)",
		"+			",
		"+			logger(",
		"+				\"Created new recording: { audio.trackPosition: {0}, layout.name: {1} }\", LogType.INFO, ",
		"+				currentRecording.audio.trackPosition, currentRecording.layout.name",
		"+			);",
		"+		},		",
		"+		stopRecording: function(eventsRecorder) {",
		"+			",
		"+			var currentRecording = eventsRecorder.getCurrentRecording(eventsRecorder);",
		"+			if (isOptionalPresent(currentRecording)) {",
		"+			",
		"+				Core.File.write({ ",
		"+					text: Core.JSON.stringify(currentRecording), ",
		"+					filename: \"recording.json\", ",
		"+					withDialog: true",
		"+				});",
		"+			}",
		"+			eventsRecorder.setCurrentRecording(eventsRecorder, null);",
		"+		},	",
		"+		registerEvent: function(eventsRecorder, event) {",
		"+			",
		"+			var currentRecording = eventsRecorder.getCurrentRecording(eventsRecorder);",
		"+			if (isStruct(currentRecording)) && (currentRecording.timer > 0) {",
		" 				",
		"-					var keyboardKey = keyboardMapping[index];",
		"-					var keyCheckResult = keyboard_check_pressed(ord(keyboardKey));",
		"-					if (keyCheckResult) {",
		"-						",
		"-						result = (index == 0) ? true : (keyCheckResult && result) == true;",
		"-					} else {",
		"+				currentRecording.events = Core.Collections._Array.push(currentRecording.events, event);",
		"+				logger(\"Event registered: {0}\", LogType.INFO, Core.JSON.stringify(event));",
		"+			}",
		"+		},",
		"+		update: function(eventsRecorder) {",
		"+			",
		"+			",
		"+			var currentRecording = eventsRecorder.getCurrentRecording(eventsRecorder);",
		"+			if (isStruct(currentRecording)) {",
		"+				//print(\"RECORDING\");",
		"+				currentRecording.timer = incrementTimer(currentRecording.timer, MAX_NUMBER);",
		"+			}",
		"+		},",
		"+		parseRecording: function(eventsRecorder, jsonString) {",
		"+		",
		"+			var eventsRecording = null;",
		"+			try {",
		"+				",
		"+				var jsonObject = Core.JSON.decode(jsonString);",
		"+				var timer = Core.Collections._Map.get(jsonObject, \"timer\");",
		"+				var events = [];",
		"+				var jsonEvents = Core.Collections._Map.get(jsonObject, \"events\");",
		"+				if (jsonEvents != null) {",
		" 					",
		"-						result = false;",
		"-						break;",
		"+					var eventsSize = Core.Collections._List.size(jsonEvents);",
		"+					for (var index = 0; index < eventsSize; index++) {",
		"+						",
		"+						var jsonEvent = Core.Collections._List.get(jsonEvents, index);",
		"+						var asd = Core.Collections._Map.get(jsonEvent, \"data\");",
		"+						var entry = {",
		"+							name: Core.Collections._Map.get(jsonEvent, \"name\"),",
		"+							data: Core.Collections._Map.toStruct(Core.Collections._Map.get(jsonEvent, \"data\"))",
		"+						}",
		"+						events = Core.Collections._Array.push(events, entry);",
		"+					}",
		"+				}",
		"+				",
		"+				eventsRecording = {",
		"+					timer: timer,",
		"+					events: events,",
		"+					audio: {",
		"+						name: getAssetName(asset_ost_boa_duvet_virtual_self, AssetSound), ///@todo mockup",
		"+						trackPosition: random(100) ///@todo mockup",
		"+					},",
		"+					layout: {",
		"+						name: \"novation-launchpad\", ///@todo mockup",
		"+						page: 0 ///@todo mockup",
		" 					}",
		" 				}",
		"+				",
		"+				Core.Collections._Map.free(jsonObject);",
		"+				//Core.File.write({ ",
		"+				//	text: Core.JSON.stringify(eventsRecording), ",
		"+				//	filename: \"recording.json\", ",
		"+				//	withDialog: true",
		"+				//});",
		"+			} catch (exception) {",
		"+				",
		"+				logger(exception.message, LogType.ERROR);",
		"+				printStackTrace();",
		" 			}",
		" 			",
		"-			return result;",
		"+			return eventsRecording;",
		"+		},",
		"+		",
		"+		getState: function(eventsRecorder) {",
		"+		",
		"+			if !isOptionalPresent(eventsRecorder.state) {",
		"+				eventsRecorder.state = {}",
		"+			}",
		"+			",
		"+			return eventsRecorder.state",
		"+		},",
		"+		getCurrentRecording: function(eventsRecorder) {",
		"+			",
		"+			return getStructVariable(eventsRecorder.getState(eventsRecorder), \"currentRecording\");",
		"+		},",
		"+		setCurrentRecording: function(eventsRecorder, currentRecording) {",
		"+		",
		"+			return setStructVariable(eventsRecorder.getState(eventsRecorder), \"currentRecording\", currentRecording);",
		" 		}",
		" 	}",
		" }",
		"@@ -268,5 +474,4 @@ function shroomButton(texture, speedValue) {",
		" 			])",
		" 		)",
		" 	);",
		"-",
		" }",
		"\\ No newline at end of file",
		"diff --git a/yyp/scripts/incrementTimer/incrementTimer.gml b/yyp/scripts/incrementTimer/incrementTimer.gml",
		"index 09eb579..6478a0e 100644",
		"--- a/yyp/scripts/incrementTimer/incrementTimer.gml",
		"+++ b/yyp/scripts/incrementTimer/incrementTimer.gml",
		"@@ -8,7 +8,7 @@ function incrementTimer() {",
		" 		///checkArgumentCount(2, argument_count, incrementTimer);",
		" ",
		" 		var value = argument[0];",
		"-		var maxValue = argument[1];",
		"+		var maxValue = argument_count > 1 ? argument[1] : MAX_NUMBER;",
		" 		var incrementBy = argument_count > 2 ? argument[2] : 1.0 / GAME_FPS;",
		" 	",
		" 		value += incrementBy * getDeltaTimeValue();",
		"diff --git a/yyp/scripts/initializeGlobals/initializeGlobals.gml b/yyp/scripts/initializeGlobals/initializeGlobals.gml",
		"index 7560f54..075ef31 100644",
		"--- a/yyp/scripts/initializeGlobals/initializeGlobals.gml",
		"+++ b/yyp/scripts/initializeGlobals/initializeGlobals.gml",
		"@@ -355,4 +355,96 @@ function initializeGlobals() {",
		" 	#macro CurrentResolution global.__CurrentResolution",
		" 	",
		" 	#endregion",
		"+	",
		"+	",
		"+	global.__core_JSON = {",
		"+	",
		"+		decode: function(value) {",
		"+			return json_decode(value);",
		"+		},",
		"+		stringify: function(value) {",
		"+			return isDataStructure(value, Map) ?",
		"+				json_encode(value) :",
		"+				json_stringify(value);",
		"+		}",
		"+	}",
		"+	global.__core_File = {",
		"+	",
		"+		write: function(data) {",
		"+			",
		"+			if (data.withDialog) {",
		"+				",
		"+				writeStringToFileDialog(data.text, data.filename, structVariableExists(data, \"extension\") ? getStructVariable(data, \"extension\") : \"\");",
		"+			} else {",
		"+			",
		"+				writeStringToFile(data.text, data.filename);",
		"+			}",
		"+		},",
		"+		read: function(data) {",
		"+		",
		"+			if (data.withDialog) {",
		"+				",
		"+				return readStringFromFileDialog();",
		"+			} else {",
		"+			",
		"+				return readStringFromFile(data.path, data.filename);",
		"+			}",
		"+		}",
		"+	}",
		"+	global.__core_Collections = {",
		"+		",
		"+		_Array: {",
		"+			push: function(array, value) {",
		"+				return pushArray(array, value)",
		"+			},",
		"+			size: function(array) {",
		"+				return getArrayLength(array);",
		"+			},",
		"+			getRandom: function(array) {",
		"+				return getRandomValueFromArray(array);",
		"+			}",
		"+		},",
		"+		_List: {",
		"+			get: function(list, index) {",
		"+				return getFromList(list, index);",
		"+			},",
		"+			size: function(list) {",
		"+				return getListSize(list);",
		"+			}",
		"+		},",
		"+		_Queue: {",
		"+			getTail: function(queue) {",
		"+				return getTailOfQueue(queue);",
		"+			}",
		"+		},",
		"+		_Map: {",
		"+			get: function(map, key) {",
		"+				return getFromMap(map, key);",
		"+			},",
		"+			clone: function(map) {",
		"+				return cloneMap(map);",
		"+			},",
		"+			toStruct: function(map) {",
		"+			",
		"+				var struct = {};",
		"+				var keys = getMapKeys(map);",
		"+				for (var index = 0; index < getArrayLength(keys); index++) {",
		"+				",
		"+					var key = keys[index];",
		"+					setStructVariable(struct, key, getFromMap(map, key))",
		"+				}",
		"+				return struct;",
		"+			},",
		"+			free: function(map) {",
		"+				destroyDataStructure(map, Map);",
		"+			}",
		"+		}",
		"+	}",
		"+	global.__core = {",
		"+	",
		"+		JSON: global.__core_JSON,",
		"+		File: global.__core_File,",
		"+		Collections: global.__core_Collections",
		"+	}",
		"+	#macro Core global.__core",
		" }",
		"diff --git a/yyp/spaace-loader.yyp b/yyp/spaace-loader.yyp",
		"index 2ce0f77..b9818cc 100644",
		"--- a/yyp/spaace-loader.yyp",
		"+++ b/yyp/spaace-loader.yyp",
		"@@ -691,7 +691,7 @@",
		" 			            keyboardMapping: [ \"2\", \"8\"],",
		" 			            pressed: function () {",
		" ",
		"-			                var color = colorHashToGMColor(\"#a81468\");",
		"+			                var color = colorHashToGMColor(\"#FFC5E0\");",
		" 							logger(\"Set colorGridBackground to: {0}\", LogType.INFO, gmColorToColorHash(color));",
		" 							setInstanceVariable(getGridRenderer(), \"colorGridBackground\", color);",
		" 			            }",
		"@@ -704,7 +704,7 @@",
		" 			            keyboardMapping: [ \"3\", \"8\" ],",
		" 			            pressed: function () {",
		" ",
		"-			            	var color = colorHashToGMColor(\"#36cf82\");",
		"+			            	var color = colorHashToGMColor(\"#9656EB\");",
		" 							logger(\"Set colorGridBackground to: {0}\", LogType.INFO, gmColorToColorHash(color));",
		" 							setInstanceVariable(getGridRenderer(), \"colorGridBackground\", color);",
		" 			            }",
		"@@ -717,7 +717,7 @@",
		" 			            keyboardMapping: [ \"4\", \"8\" ],",
		" 			            pressed: function () {",
		" ",
		"-			            	var color = colorHashToGMColor(\"#285bde\");",
		"+			            	var color = colorHashToGMColor(\"#FA6696\");",
		" 							logger(\"Set colorGridBackground to: {0}\", LogType.INFO, gmColorToColorHash(color));",
		" 							setInstanceVariable(getGridRenderer(), \"colorGridBackground\", color);",
		" 			            }",
		"@@ -845,6 +845,32 @@",
		" 			            keyboardMapping: [ \"Z\", \"8\" ],",
		" 			            pressed: function () {",
		" ",
		"+							var result = Core.Collections._Array.getRandom([",
		"+								{",
		"+								    firstBlendPointer: 1,",
		"+								    secondBlendPointer: 0",
		"+								},",
		"+								{",
		"+								    firstBlendPointer: 0,",
		"+								    secondBlendPointer: 1",
		"+								},",
		"+								{",
		"+								    firstBlendPointer: 2,",
		"+								    secondBlendPointer: 1",
		"+								},",
		"+								{",
		"+								    firstBlendPointer: 9,",
		"+								    secondBlendPointer: 0",
		"+								},",
		"+								{",
		"+								    firstBlendPointer: 7,",
		"+								    secondBlendPointer: 1",
		"+								}",
		"+							]);",
		"+",
		"+							setInstanceVariable(getGridRenderer(), \"firstBlendPointer\", result.firstBlendPointer);",
		"+							setInstanceVariable(getGridRenderer(), \"secondBlendPointer\", result.secondBlendPointer);",
		"+							logger(\"set Blend modes: {0}x{1}\", LogType.INFO, result.firstBlendPointer, result.secondBlendPointer);",
		" 			            }",
		" 			        }",
		" 			    ),",
		"@@ -104,7 +104,7 @@",
		"     {\"id\":{\"name\":\"getAudioContextSound\",\"path\":\"scripts/getAudioContextSound/getAudioContextSound.yy\",},\"order\":5,},",
		"     {\"id\":{\"name\":\"getAudioContextStatus\",\"path\":\"scripts/getAudioContextStatus/getAudioContextStatus.yy\",},\"order\":7,},",
		"     {\"id\":{\"name\":\"setAudioContextName\",\"path\":\"scripts/setAudioContextName/setAudioContextName.yy\",},\"order\":1,},",
		"-    {\"id\":{\"name\":\"asset_texture_cirno_01\",\"path\":\"sprites/asset_texture_cirno_01/asset_texture_cirno_01.yy\",},\"order\":23,},",
		"+    {\"id\":{\"name\":\"asset_texture_cirno_01\",\"path\":\"sprites/asset_texture_cirno_01/asset_texture_cirno_01.yy\",},\"order\":14,},",
		"     {\"id\":{\"name\":\"setAudioContextAsset\",\"path\":\"scripts/setAudioContextAsset/setAudioContextAsset.yy\",},\"order\":3,},",
		"     {\"id\":{\"name\":\"setAudioContextSound\",\"path\":\"scripts/setAudioContextSound/setAudioContextSound.yy\",},\"order\":5,},",
		"     {\"id\":{\"name\":\"setAudioContextStatus\",\"path\":\"scripts/setAudioContextStatus/setAudioContextStatus.yy\",},\"order\":7,},",
		"@@ -181,7 +181,7 @@",
		"     {\"id\":{\"name\":\"deserializeLayerGroup\",\"path\":\"scripts/deserializeLayerGroup/deserializeLayerGroup.yy\",},\"order\":9,},",
		"     {\"id\":{\"name\":\"destroyLayerGroup\",\"path\":\"scripts/destroyLayerGroup/destroyLayerGroup.yy\",},\"order\":11,},",
		"     {\"id\":{\"name\":\"getSpriteColor\",\"path\":\"scripts/getSpriteColor/getSpriteColor.yy\",},\"order\":1,},",
		"-    {\"id\":{\"name\":\"asset_texture_cross_anime_2009_01\",\"path\":\"sprites/asset_texture_cross_anime_2009_01/asset_texture_cross_anime_2009_01.yy\",},\"order\":7,},",
		"+    {\"id\":{\"name\":\"asset_texture_cross_anime_2009_01\",\"path\":\"sprites/asset_texture_cross_anime_2009_01/asset_texture_cross_anime_2009_01.yy\",},\"order\":5,},",
		"     {\"id\":{\"name\":\"getSpriteAngle\",\"path\":\"scripts/getSpriteAngle/getSpriteAngle.yy\",},\"order\":3,},",
		"     {\"id\":{\"name\":\"getSpriteAlpha\",\"path\":\"scripts/getSpriteAlpha/getSpriteAlpha.yy\",},\"order\":5,},",
		"     {\"id\":{\"name\":\"getSpriteYScale\",\"path\":\"scripts/getSpriteYScale/getSpriteYScale.yy\",},\"order\":7,},",
		"@@ -359,6 +359,7 @@",
		"     {\"id\":{\"name\":\"getMouseViewContainerUiManager\",\"path\":\"scripts/getMouseViewContainerUiManager/getMouseViewContainerUiManager.yy\",},\"order\":9,},",
		"     {\"id\":{\"name\":\"setMouseViewContainerName\",\"path\":\"scripts/setMouseViewContainerName/setMouseViewContainerName.yy\",},\"order\":1,},",
		"     {\"id\":{\"name\":\"setMouseViewContainerArea\",\"path\":\"scripts/setMouseViewContainerArea/setMouseViewContainerArea.yy\",},\"order\":3,},",
		"+    {\"id\":{\"name\":\"asset_texture_kanro_euphoria_catgirl_01\",\"path\":\"sprites/asset_texture_kanro_euphoria_catgirl_01/asset_texture_kanro_euphoria_catgirl_01.yy\",},\"order\":0,},",
		"     {\"id\":{\"name\":\"setMouseViewContainerMouseActions\",\"path\":\"scripts/setMouseViewContainerMouseActions/setMouseViewContainerMouseActions.yy\",},\"order\":5,},",
		"     {\"id\":{\"name\":\"setMouseViewContainerMouseActionEventHandler\",\"path\":\"scripts/setMouseViewContainerMouseActionEventHandler/setMouseViewContainerMouseActionEventHandler.yy\",},\"order\":7,},",
		"     {\"id\":{\"name\":\"setMouseViewContainerUiManager\",\"path\":\"scripts/setMouseViewContainerUiManager/setMouseViewContainerUiManager.yy\",},\"order\":9,},",
		"@@ -437,7 +438,7 @@",
		"     {\"id\":{\"name\":\"serializeChronosEvent\",\"path\":\"scripts/serializeChronosEvent/serializeChronosEvent.yy\",},\"order\":7,},",
		"     {\"id\":{\"name\":\"deserializeChronosEvent\",\"path\":\"scripts/deserializeChronosEvent/deserializeChronosEvent.yy\",},\"order\":9,},",
		"     {\"id\":{\"name\":\"destroyChronosEvent\",\"path\":\"scripts/destroyChronosEvent/destroyChronosEvent.yy\",},\"order\":11,},",
		"-    {\"id\":{\"name\":\"asset_texture_cross_pokemon_01\",\"path\":\"sprites/asset_texture_cross_pokemon_01/asset_texture_cross_pokemon_01.yy\",},\"order\":8,},",
		"+    {\"id\":{\"name\":\"asset_texture_cross_pokemon_01\",\"path\":\"sprites/asset_texture_cross_pokemon_01/asset_texture_cross_pokemon_01.yy\",},\"order\":6,},",
		"     {\"id\":{\"name\":\"getChronosTaskTimer\",\"path\":\"scripts/getChronosTaskTimer/getChronosTaskTimer.yy\",},\"order\":1,},",
		"     {\"id\":{\"name\":\"getChronosTaskDuration\",\"path\":\"scripts/getChronosTaskDuration/getChronosTaskDuration.yy\",},\"order\":3,},",
		"     {\"id\":{\"name\":\"getChronosTaskChronosEvent\",\"path\":\"scripts/getChronosTaskChronosEvent/getChronosTaskChronosEvent.yy\",},\"order\":5,},",
		"@@ -686,6 +687,7 @@",
		"     {\"id\":{\"name\":\"createConsoleCommand\",\"path\":\"scripts/createConsoleCommand/createConsoleCommand.yy\",},\"order\":5,},",
		"     {\"id\":{\"name\":\"serializeConsoleCommand\",\"path\":\"scripts/serializeConsoleCommand/serializeConsoleCommand.yy\",},\"order\":7,},",
		"     {\"id\":{\"name\":\"deserializeConsoleCommand\",\"path\":\"scripts/deserializeConsoleCommand/deserializeConsoleCommand.yy\",},\"order\":9,},",
		"+    {\"id\":{\"name\":\"asset_texture_cirno_02\",\"path\":\"sprites/asset_texture_cirno_02/asset_texture_cirno_02.yy\",},\"order\":13,},",
		"     {\"id\":{\"name\":\"destroyConsoleCommand\",\"path\":\"scripts/destroyConsoleCommand/destroyConsoleCommand.yy\",},\"order\":11,},",
		"     {\"id\":{\"name\":\"getExceptionName\",\"path\":\"scripts/getExceptionName/getExceptionName.yy\",},\"order\":1,},",
		"     {\"id\":{\"name\":\"getExceptionMessage\",\"path\":\"scripts/getExceptionMessage/getExceptionMessage.yy\",},\"order\":3,},",
		"@@ -908,7 +910,7 @@",
		"     {\"id\":{\"name\":\"destroyMouseEvent\",\"path\":\"scripts/destroyMouseEvent/destroyMouseEvent.yy\",},\"order\":11,},",
		"     {\"id\":{\"name\":\"getMarginTop\",\"path\":\"scripts/getMarginTop/getMarginTop.yy\",},\"order\":1,},",
		"     {\"id\":{\"name\":\"shdBktGlitch\",\"path\":\"shaders/shdBktGlitch/shdBktGlitch.yy\",},\"order\":0,},",
		"-    {\"id\":{\"name\":\"asset_texture_cross_monkey\",\"path\":\"sprites/asset_texture_cross_monkey/asset_texture_cross_monkey.yy\",},\"order\":6,},",
		"+    {\"id\":{\"name\":\"asset_texture_cross_monkey\",\"path\":\"sprites/asset_texture_cross_monkey/asset_texture_cross_monkey.yy\",},\"order\":4,},",
		"     {\"id\":{\"name\":\"getMarginRight\",\"path\":\"scripts/getMarginRight/getMarginRight.yy\",},\"order\":3,},",
		"     {\"id\":{\"name\":\"getMarginBottom\",\"path\":\"scripts/getMarginBottom/getMarginBottom.yy\",},\"order\":5,},",
		"     {\"id\":{\"name\":\"getMarginLeft\",\"path\":\"scripts/getMarginLeft/getMarginLeft.yy\",},\"order\":7,},",
		"@@ -1054,7 +1056,7 @@",
		"     {\"id\":{\"name\":\"getTypeOfNested\",\"path\":\"scripts/getTypeOfNested/getTypeOfNested.yy\",},\"order\":3,},",
		"     {\"id\":{\"name\":\"typeOf\",\"path\":\"scripts/typeOf/typeOf.yy\",},\"order\":3,},",
		"     {\"id\":{\"name\":\"isNestedType\",\"path\":\"scripts/isNestedType/isNestedType.yy\",},\"order\":5,},",
		"-    {\"id\":{\"name\":\"asset_texture_cross_anime_2009_03\",\"path\":\"sprites/asset_texture_cross_anime_2009_03/asset_texture_cross_anime_2009_03.yy\",},\"order\":11,},",
		"+    {\"id\":{\"name\":\"asset_texture_cross_anime_2009_03\",\"path\":\"sprites/asset_texture_cross_anime_2009_03/asset_texture_cross_anime_2009_03.yy\",},\"order\":9,},",
		"     {\"id\":{\"name\":\"cast\",\"path\":\"scripts/cast/cast.yy\",},\"order\":3,},",
		"     {\"id\":{\"name\":\"super\",\"path\":\"scripts/super/super.yy\",},\"order\":3,},",
		"     {\"id\":{\"name\":\"instanceOf\",\"path\":\"scripts/instanceOf/instanceOf.yy\",},\"order\":5,},",
		"@@ -1083,7 +1085,7 @@",
		"     {\"id\":{\"name\":\"matchAny\",\"path\":\"scripts/matchAny/matchAny.yy\",},\"order\":5,},",
		"     {\"id\":{\"name\":\"defaultContextInstanceConstructor\",\"path\":\"scripts/defaultContextInstanceConstructor/defaultContextInstanceConstructor.yy\",},\"order\":1,},",
		"     {\"id\":{\"name\":\"compatibility_report_210322_1954105410\",\"path\":\"notes/compatibility_report_210322_1954105410/compatibility_report_210322_1954105410.yy\",},\"order\":0,},",
		"-    {\"id\":{\"name\":\"asset_texture_cross_cat_01\",\"path\":\"sprites/asset_texture_cross_cat_01/asset_texture_cross_cat_01.yy\",},\"order\":10,},",
		"+    {\"id\":{\"name\":\"asset_texture_cross_cat_01\",\"path\":\"sprites/asset_texture_cross_cat_01/asset_texture_cross_cat_01.yy\",},\"order\":8,},",
		"     {\"id\":{\"name\":\"deregisterContext\",\"path\":\"scripts/deregisterContext/deregisterContext.yy\",},\"order\":3,},",
		"     {\"id\":{\"name\":\"registerContext\",\"path\":\"scripts/registerContext/registerContext.yy\",},\"order\":5,},",
		"     {\"id\":{\"name\":\"runtimeExceptionHandler\",\"path\":\"scripts/runtimeExceptionHandler/runtimeExceptionHandler.yy\",},\"order\":1,},",
		"@@ -1192,7 +1194,7 @@",
		"     {\"id\":{\"name\":\"getRightAngle\",\"path\":\"scripts/getRightAngle/getRightAngle.yy\",},\"order\":21,},",
		"     {\"id\":{\"name\":\"coordsInRectangle\",\"path\":\"scripts/coordsInRectangle/coordsInRectangle.yy\",},\"order\":23,},",
		"     {\"id\":{\"name\":\"isNumber\",\"path\":\"scripts/isNumber/isNumber.yy\",},\"order\":1,},",
		"-    {\"id\":{\"name\":\"asset_texture_cross_anime_2009_04\",\"path\":\"sprites/asset_texture_cross_anime_2009_04/asset_texture_cross_anime_2009_04.yy\",},\"order\":13,},",
		"+    {\"id\":{\"name\":\"asset_texture_cross_anime_2009_04\",\"path\":\"sprites/asset_texture_cross_anime_2009_04/asset_texture_cross_anime_2009_04.yy\",},\"order\":11,},",
		"     {\"id\":{\"name\":\"isStringNumber\",\"path\":\"scripts/isStringNumber/isStringNumber.yy\",},\"order\":3,},",
		"     {\"id\":{\"name\":\"centerCoord\",\"path\":\"scripts/centerCoord/centerCoord.yy\",},\"order\":5,},",
		"     {\"id\":{\"name\":\"getNumber\",\"path\":\"scripts/getNumber/getNumber.yy\",},\"order\":7,},",
		"@@ -1624,6 +1626,7 @@",
		"     {\"id\":{\"name\":\"getReactorNextElement\",\"path\":\"scripts/getReactorNextElement/getReactorNextElement.yy\",},\"order\":9,},",
		"     {\"id\":{\"name\":\"removeReactorElement\",\"path\":\"scripts/removeReactorElement/removeReactorElement.yy\",},\"order\":11,},",
		"     {\"id\":{\"name\":\"addElementToReactor\",\"path\":\"scripts/addElementToReactor/addElementToReactor.yy\",},\"order\":13,},",
		"+    {\"id\":{\"name\":\"asset_texture_kanro_euphoria_insta\",\"path\":\"sprites/asset_texture_kanro_euphoria_insta/asset_texture_kanro_euphoria_insta.yy\",},\"order\":1,},",
		"     {\"id\":{\"name\":\"resolveReactor\",\"path\":\"scripts/resolveReactor/resolveReactor.yy\",},\"order\":15,},",
		"     {\"id\":{\"name\":\"destroyDataStructure\",\"path\":\"scripts/destroyDataStructure/destroyDataStructure.yy\",},\"order\":23,},",
		"     {\"id\":{\"name\":\"isDataStructure\",\"path\":\"scripts/isDataStructure/isDataStructure.yy\",},\"order\":25,},",
		"@@ -1703,7 +1706,7 @@",
		"     {\"id\":{\"name\":\"getParticleTaskPositionEnd\",\"path\":\"scripts/getParticleTaskPositionEnd/getParticleTaskPositionEnd.yy\",},\"order\":1,},",
		"     {\"id\":{\"name\":\"getParticleTaskPositionBegin\",\"path\":\"scripts/getParticleTaskPositionBegin/getParticleTaskPositionBegin.yy\",},\"order\":3,},",
		"     {\"id\":{\"name\":\"getParticleTaskEmitterTimer\",\"path\":\"scripts/getParticleTaskEmitterTimer/getParticleTaskEmitterTimer.yy\",},\"order\":5,},",
		"-    {\"id\":{\"name\":\"asset_texture_cross_butterfly\",\"path\":\"sprites/asset_texture_cross_butterfly/asset_texture_cross_butterfly.yy\",},\"order\":5,},",
		"+    {\"id\":{\"name\":\"asset_texture_cross_butterfly\",\"path\":\"sprites/asset_texture_cross_butterfly/asset_texture_cross_butterfly.yy\",},\"order\":3,},",
		"     {\"id\":{\"name\":\"getParticleTaskEmitterInterval\",\"path\":\"scripts/getParticleTaskEmitterInterval/getParticleTaskEmitterInterval.yy\",},\"order\":7,},",
		"     {\"id\":{\"name\":\"getParticleTaskDuration\",\"path\":\"scripts/getParticleTaskDuration/getParticleTaskDuration.yy\",},\"order\":9,},",
		"     {\"id\":{\"name\":\"getParticleTaskTimer\",\"path\":\"scripts/getParticleTaskTimer/getParticleTaskTimer.yy\",},\"order\":11,},",
		"@@ -1845,7 +1848,7 @@",
		"     {\"id\":{\"name\":\"createShaderTask\",\"path\":\"scripts/createShaderTask/createShaderTask.yy\",},\"order\":7,},",
		"     {\"id\":{\"name\":\"setShaderTaskCooldown\",\"path\":\"scripts/setShaderTaskCooldown/setShaderTaskCooldown.yy\",},\"order\":1,},",
		"     {\"id\":{\"name\":\"setShaderTaskAlpha\",\"path\":\"scripts/setShaderTaskAlpha/setShaderTaskAlpha.yy\",},\"order\":3,},",
		"-    {\"id\":{\"name\":\"asset_texture_cross_anime_2009_02\",\"path\":\"sprites/asset_texture_cross_anime_2009_02/asset_texture_cross_anime_2009_02.yy\",},\"order\":12,},",
		"+    {\"id\":{\"name\":\"asset_texture_cross_anime_2009_02\",\"path\":\"sprites/asset_texture_cross_anime_2009_02/asset_texture_cross_anime_2009_02.yy\",},\"order\":10,},",
		"     {\"id\":{\"name\":\"setShaderTaskState\",\"path\":\"scripts/setShaderTaskState/setShaderTaskState.yy\",},\"order\":5,},",
		"     {\"id\":{\"name\":\"setShaderTaskCountdown\",\"path\":\"scripts/setShaderTaskCountdown/setShaderTaskCountdown.yy\",},\"order\":7,},",
		"     {\"id\":{\"name\":\"setShaderTaskShader\",\"path\":\"scripts/setShaderTaskShader/setShaderTaskShader.yy\",},\"order\":9,},",
		"@@ -1861,10 +1864,10 @@",
		"     {\"id\":{\"name\":\"setShaderPipelineLimit\",\"path\":\"scripts/setShaderPipelineLimit/setShaderPipelineLimit.yy\",},\"order\":1,},",
		"     {\"id\":{\"name\":\"setShaderPipelineBuffer\",\"path\":\"scripts/setShaderPipelineBuffer/setShaderPipelineBuffer.yy\",},\"order\":3,},",
		"     {\"id\":{\"name\":\"getShroomText\",\"path\":\"scripts/getShroomText/getShroomText.yy\",},\"order\":11,},",
		"-    {\"id\":{\"name\":\"asset_texture_cross_cross\",\"path\":\"sprites/asset_texture_cross_cross/asset_texture_cross_cross.yy\",},\"order\":9,},",
		"+    {\"id\":{\"name\":\"asset_texture_cross_cross\",\"path\":\"sprites/asset_texture_cross_cross/asset_texture_cross_cross.yy\",},\"order\":7,},",
		"     {\"id\":{\"name\":\"setShaderPipelinePipe\",\"path\":\"scripts/setShaderPipelinePipe/setShaderPipelinePipe.yy\",},\"order\":5,},",
		"     {\"id\":{\"name\":\"getShaderPipelineLimit\",\"path\":\"scripts/getShaderPipelineLimit/getShaderPipelineLimit.yy\",},\"order\":1,},",
		"-    {\"id\":{\"name\":\"asset_texture_alka_glitch_01\",\"path\":\"sprites/asset_texture_alka_glitch_01/asset_texture_alka_glitch_01.yy\",},\"order\":4,},",
		"+    {\"id\":{\"name\":\"asset_texture_alka_glitch_01\",\"path\":\"sprites/asset_texture_alka_glitch_01/asset_texture_alka_glitch_01.yy\",},\"order\":2,},",
		"     {\"id\":{\"name\":\"getShaderPipelineBuffer\",\"path\":\"scripts/getShaderPipelineBuffer/getShaderPipelineBuffer.yy\",},\"order\":3,},",
		"     {\"id\":{\"name\":\"getShaderPipelinePipe\",\"path\":\"scripts/getShaderPipelinePipe/getShaderPipelinePipe.yy\",},\"order\":5,},",
		"     {\"id\":{\"name\":\"destroyShaderEvent\",\"path\":\"scripts/destroyShaderEvent/destroyShaderEvent.yy\",},\"order\":1,},",
		"@@ -2888,7 +2891,7 @@",
		"     {\"folderPath\":\"folders/src/com.devhorizon.core/instance/TouchInputHandler.yy\",\"order\":9,\"resourceVersion\":\"1.0\",\"name\":\"TouchInputHandler\",\"tags\":[],\"resourceType\":\"GMFolder\",},",
		"     {\"folderPath\":\"folders/src/com.devhorizon.core/lang/reflection/instance.yy\",\"order\":16,\"resourceVersion\":\"1.0\",\"name\":\"instance\",\"tags\":[],\"resourceType\":\"GMFolder\",},",
		"     {\"folderPath\":\"folders/src/com.devhorizon.core/lang/reflection/struct.yy\",\"order\":17,\"resourceVersion\":\"1.0\",\"name\":\"struct\",\"tags\":[],\"resourceType\":\"GMFolder\",},",
		"-    {\"folderPath\":\"folders/asset/com.devhorizon.spaaceloader.yy\",\"order\":3,\"resourceVersion\":\"1.0\",\"name\":\"com.devhorizon.spaaceloader\",\"tags\":[],\"resourceType\":\"GMFolder\",},",
		"+    {\"folderPath\":\"folders/asset/com.devhorizon.spaaceloader.yy\",\"order\":1,\"resourceVersion\":\"1.0\",\"name\":\"com.devhorizon.spaaceloader\",\"tags\":[],\"resourceType\":\"GMFolder\",},",
		"     {\"folderPath\":\"folders/src/com.devhorizon.spaaceloader.yy\",\"order\":3,\"resourceVersion\":\"1.0\",\"name\":\"com.devhorizon.spaaceloader\",\"tags\":[],\"resourceType\":\"GMFolder\",},",
		"     {\"folderPath\":\"folders/src/com.devhorizon.spaaceloader/boot.yy\",\"order\":0,\"resourceVersion\":\"1.0\",\"name\":\"boot\",\"tags\":[],\"resourceType\":\"GMFolder\",},",
		"     {\"folderPath\":\"folders/asset/com.devhorizon.spaaceloader/scene.yy\",\"order\":0,\"resourceVersion\":\"1.0\",\"name\":\"scene\",\"tags\":[],\"resourceType\":\"GMFolder\",},",
		"@@ -2912,6 +2915,8 @@",
		"     {\"folderPath\":\"folders/com.janvorisek.bktglitch/Sprites/demo (IGNORE).yy\",\"order\":1,\"resourceVersion\":\"1.0\",\"name\":\"demo (IGNORE)\",\"tags\":[],\"resourceType\":\"GMFolder\",},",
		"     {\"folderPath\":\"folders/com.janvorisek.bktglitch.yy\",\"order\":41,\"resourceVersion\":\"1.0\",\"name\":\"com.janvorisek.bktglitch\",\"tags\":[],\"resourceType\":\"GMFolder\",},",
		"     {\"folderPath\":\"folders/Notes.yy\",\"order\":43,\"resourceVersion\":\"1.0\",\"name\":\"Notes\",\"tags\":[],\"resourceType\":\"GMFolder\",},",
		"+    {\"folderPath\":\"folders/asset/kanro_euphoria_theaster_remix.yy\",\"order\":12,\"resourceVersion\":\"1.0\",\"name\":\"kanro_euphoria_theaster_remix\",\"tags\":[],\"resourceType\":\"GMFolder\",},",
		"+    {\"folderPath\":\"folders/src/com.devhorizon.spaaceloader/entity/group1.yy\",\"order\":54,\"resourceVersion\":\"1.0\",\"name\":\"group1\",\"tags\":[],\"resourceType\":\"GMFolder\",},",
		"   ],",
		"   \"AudioGroups\": [",
		"     {\"targets\":-1,\"resourceVersion\":\"1.3\",\"name\":\"audiogroup_default\",\"resourceType\":\"GMAudioGroup\",},",
		"diff --git a/yyp/sprites/asset_texture_cirno_01/asset_texture_cirno_01.yy b/yyp/sprites/asset_texture_cirno_01/asset_texture_cirno_01.yy",
		"index 1dbf7db..440e5c8 100644",
		"--- a/yyp/sprites/asset_texture_cirno_01/asset_texture_cirno_01.yy",
		"+++ b/yyp/sprites/asset_texture_cirno_01/asset_texture_cirno_01.yy",
		"@@ -69,8 +69,8 @@",
		"   ],",
		"   \"nineSlice\": null,",
		"   \"parent\": {",
		"-    \"name\": \"texture\",",
		"-    \"path\": \"folders/asset/com.devhorizon.spaaceloader/texture.yy\",",
		"+    \"name\": \"asset\",",
		"+    \"path\": \"folders/asset.yy\",",
		"   },",
		"   \"resourceVersion\": \"1.0\",",
		"   \"name\": \"asset_texture_cirno_01\",",
		"diff --git a/yyp/sprites/asset_texture_cross_anime_2009_01/641b9b68-a873-4a01-90bb-c37cff0ee62b.png b/yyp/sprites/asset_texture_cross_anime_2009_01/641b9b68-a873-4a01-90bb-c37cff0ee62b.png",
		"deleted file mode 100644",
		"index 82d8f54..0000000",
		"Binary files a/yyp/sprites/asset_texture_cross_anime_2009_01/641b9b68-a873-4a01-90bb-c37cff0ee62b.png and /dev/null differ",
		"diff --git a/yyp/sprites/asset_texture_cross_anime_2009_01/asset_texture_cross_anime_2009_01.yy b/yyp/sprites/asset_texture_cross_anime_2009_01/asset_texture_cross_anime_2009_01.yy",
		"index d772d34..f03660c 100644",
		"--- a/yyp/sprites/asset_texture_cross_anime_2009_01/asset_texture_cross_anime_2009_01.yy",
		"+++ b/yyp/sprites/asset_texture_cross_anime_2009_01/asset_texture_cross_anime_2009_01.yy",
		"@@ -8,14 +8,14 @@",
		"   \"collisionTolerance\": 0,",
		"   \"swfPrecision\": 2.525,",
		"   \"bbox_left\": 0,",
		"-  \"bbox_right\": 499,",
		"+  \"bbox_right\": 1724,",
		"   \"bbox_top\": 0,",
		"-  \"bbox_bottom\": 280,",
		"+  \"bbox_bottom\": 1079,",
		"   \"HTile\": false,",
		"   \"VTile\": false,",
		"   \"For3D\": false,",
		"-  \"width\": 500,",
		"-  \"height\": 281,",
		"+  \"width\": 1725,",
		"+  \"height\": 1080,",
		"   \"textureGroupId\": {",
		"     \"name\": \"Default\",",
		"     \"path\": \"texturegroups/Default\",",
		"@@ -24,9 +24,9 @@",
		"   \"gridX\": 0,",
		"   \"gridY\": 0,",
		"   \"frames\": [",
		"-    {\"compositeImage\":{\"FrameId\":{\"name\":\"641b9b68-a873-4a01-90bb-c37cff0ee62b\",\"path\":\"sprites/asset_texture_cross_anime_2009_01/asset_texture_cross_anime_2009_01.yy\",},\"LayerId\":null,\"resourceVersion\":\"1.0\",\"name\":\"\",\"tags\":[],\"resourceType\":\"GMSpriteBitmap\",},\"images\":[",
		"-        {\"FrameId\":{\"name\":\"641b9b68-a873-4a01-90bb-c37cff0ee62b\",\"path\":\"sprites/asset_texture_cross_anime_2009_01/asset_texture_cross_anime_2009_01.yy\",},\"LayerId\":{\"name\":\"0a0d2e80-1a27-43f9-9ad6-6aa81de2819c\",\"path\":\"sprites/asset_texture_cross_anime_2009_01/asset_texture_cross_anime_2009_01.yy\",},\"resourceVersion\":\"1.0\",\"name\":\"\",\"tags\":[],\"resourceType\":\"GMSpriteBitmap\",},",
		"-      ],\"parent\":{\"name\":\"asset_texture_cross_anime_2009_01\",\"path\":\"sprites/asset_texture_cross_anime_2009_01/asset_texture_cross_anime_2009_01.yy\",},\"resourceVersion\":\"1.0\",\"name\":\"641b9b68-a873-4a01-90bb-c37cff0ee62b\",\"tags\":[],\"resourceType\":\"GMSpriteFrame\",},",
		"+    {\"compositeImage\":{\"FrameId\":{\"name\":\"13198f7a-e193-4879-90bf-3616740788ac\",\"path\":\"sprites/asset_texture_cross_anime_2009_01/asset_texture_cross_anime_2009_01.yy\",},\"LayerId\":null,\"resourceVersion\":\"1.0\",\"name\":\"\",\"tags\":[],\"resourceType\":\"GMSpriteBitmap\",},\"images\":[",
		"+        {\"FrameId\":{\"name\":\"13198f7a-e193-4879-90bf-3616740788ac\",\"path\":\"sprites/asset_texture_cross_anime_2009_01/asset_texture_cross_anime_2009_01.yy\",},\"LayerId\":{\"name\":\"29e0b714-6ca8-4925-9d34-c5c342c895d5\",\"path\":\"sprites/asset_texture_cross_anime_2009_01/asset_texture_cross_anime_2009_01.yy\",},\"resourceVersion\":\"1.0\",\"name\":\"\",\"tags\":[],\"resourceType\":\"GMSpriteBitmap\",},",
		"+      ],\"parent\":{\"name\":\"asset_texture_cross_anime_2009_01\",\"path\":\"sprites/asset_texture_cross_anime_2009_01/asset_texture_cross_anime_2009_01.yy\",},\"resourceVersion\":\"1.0\",\"name\":\"13198f7a-e193-4879-90bf-3616740788ac\",\"tags\":[],\"resourceType\":\"GMSpriteFrame\",},",
		"   ],",
		"   \"sequence\": {",
		"     \"spriteId\": {\"name\":\"asset_texture_cross_anime_2009_01\",\"path\":\"sprites/asset_texture_cross_anime_2009_01/asset_texture_cross_anime_2009_01.yy\",},",
		"@@ -41,7 +41,7 @@",
		"     \"moments\": {\"Keyframes\":[],\"resourceVersion\":\"1.0\",\"resourceType\":\"KeyframeStore<MomentsEventKeyframe>\",},",
		"     \"tracks\": [",
		"       {\"name\":\"frames\",\"spriteId\":null,\"keyframes\":{\"Keyframes\":[",
		"-            {\"id\":\"e28b0676-9069-4b57-ad20-f8f0630b1b88\",\"Key\":0.0,\"Length\":1.0,\"Stretch\":false,\"Disabled\":false,\"IsCreationKey\":false,\"Channels\":{\"0\":{\"Id\":{\"name\":\"641b9b68-a873-4a01-90bb-c37cff0ee62b\",\"path\":\"sprites/asset_texture_cross_anime_2009_01/asset_texture_cross_anime_2009_01.yy\",},\"resourceVersion\":\"1.0\",\"resourceType\":\"SpriteFrameKeyframe\",},},\"resourceVersion\":\"1.0\",\"resourceType\":\"Keyframe<SpriteFrameKeyframe>\",},",
		"+            {\"id\":\"b8191591-08e4-4380-aed1-74c76ae38f6b\",\"Key\":0.0,\"Length\":1.0,\"Stretch\":false,\"Disabled\":false,\"IsCreationKey\":false,\"Channels\":{\"0\":{\"Id\":{\"name\":\"13198f7a-e193-4879-90bf-3616740788ac\",\"path\":\"sprites/asset_texture_cross_anime_2009_01/asset_texture_cross_anime_2009_01.yy\",},\"resourceVersion\":\"1.0\",\"resourceType\":\"SpriteFrameKeyframe\",},},\"resourceVersion\":\"1.0\",\"resourceType\":\"Keyframe<SpriteFrameKeyframe>\",},",
		"           ],\"resourceVersion\":\"1.0\",\"resourceType\":\"KeyframeStore<SpriteFrameKeyframe>\",},\"trackColour\":0,\"inheritsTrackColour\":true,\"builtinName\":0,\"traits\":0,\"interpolation\":1,\"tracks\":[],\"events\":[],\"isCreationTrack\":false,\"resourceVersion\":\"1.0\",\"tags\":[],\"resourceType\":\"GMSpriteFramesTrack\",\"modifiers\":[],},",
		"     ],",
		"     \"visibleRange\": null,",
		"@@ -65,7 +65,7 @@",
		"     \"resourceType\": \"GMSequence\",",
		"   },",
		"   \"layers\": [",
		"-    {\"visible\":true,\"isLocked\":false,\"blendMode\":0,\"opacity\":100.0,\"displayName\":\"default\",\"resourceVersion\":\"1.0\",\"name\":\"0a0d2e80-1a27-43f9-9ad6-6aa81de2819c\",\"tags\":[],\"resourceType\":\"GMImageLayer\",},",
		"+    {\"visible\":true,\"isLocked\":false,\"blendMode\":0,\"opacity\":100.0,\"displayName\":\"default\",\"resourceVersion\":\"1.0\",\"name\":\"29e0b714-6ca8-4925-9d34-c5c342c895d5\",\"tags\":[],\"resourceType\":\"GMImageLayer\",},",
		"   ],",
		"   \"nineSlice\": null,",
		"   \"parent\": {",
		"diff --git a/yyp/sprites/asset_texture_cross_anime_2009_01/layers/641b9b68-a873-4a01-90bb-c37cff0ee62b/0a0d2e80-1a27-43f9-9ad6-6aa81de2819c.png b/yyp/sprites/asset_texture_cross_anime_2009_01/layers/641b9b68-a873-4a01-90bb-c37cff0ee62b/0a0d2e80-1a27-43f9-9ad6-6aa81de2819c.png",
		"deleted file mode 100644",
		"index 82d8f54..0000000",
		"Binary files a/yyp/sprites/asset_texture_cross_anime_2009_01/layers/641b9b68-a873-4a01-90bb-c37cff0ee62b/0a0d2e80-1a27-43f9-9ad6-6aa81de2819c.png and /dev/null differ",
		"diff --git a/yyp/sprites/asset_texture_cross_anime_2009_02/asset_texture_cross_anime_2009_02.yy b/yyp/sprites/asset_texture_cross_anime_2009_02/asset_texture_cross_anime_2009_02.yy",
		"index f1bb038..b0df03f 100644",
		"--- a/yyp/sprites/asset_texture_cross_anime_2009_02/asset_texture_cross_anime_2009_02.yy",
		"+++ b/yyp/sprites/asset_texture_cross_anime_2009_02/asset_texture_cross_anime_2009_02.yy",
		"@@ -7,15 +7,15 @@",
		"   \"edgeFiltering\": false,",
		"   \"collisionTolerance\": 0,",
		"   \"swfPrecision\": 2.525,",
		"-  \"bbox_left\": 77,",
		"-  \"bbox_right\": 979,",
		"-  \"bbox_top\": 73,",
		"-  \"bbox_bottom\": 973,",
		"+  \"bbox_left\": 0,",
		"+  \"bbox_right\": 1725,",
		"+  \"bbox_top\": 0,",
		"+  \"bbox_bottom\": 1079,",
		"   \"HTile\": false,",
		"   \"VTile\": false,",
		"   \"For3D\": false,",
		"-  \"width\": 1024,",
		"-  \"height\": 1024,",
		"+  \"width\": 1726,",
		"+  \"height\": 1080,",
		"   \"textureGroupId\": {",
		"     \"name\": \"Default\",",
		"     \"path\": \"texturegroups/Default\",",
		"@@ -24,9 +24,9 @@",
		"   \"gridX\": 0,",
		"   \"gridY\": 0,",
		"   \"frames\": [",
		"-    {\"compositeImage\":{\"FrameId\":{\"name\":\"dcf33cc9-92a5-41d4-a378-20e3d1e2c4d3\",\"path\":\"sprites/asset_texture_cross_anime_2009_02/asset_texture_cross_anime_2009_02.yy\",},\"LayerId\":null,\"resourceVersion\":\"1.0\",\"name\":\"\",\"tags\":[],\"resourceType\":\"GMSpriteBitmap\",},\"images\":[",
		"-        {\"FrameId\":{\"name\":\"dcf33cc9-92a5-41d4-a378-20e3d1e2c4d3\",\"path\":\"sprites/asset_texture_cross_anime_2009_02/asset_texture_cross_anime_2009_02.yy\",},\"LayerId\":{\"name\":\"9030ecf9-8184-4ef1-a6b1-186a1ffcf5ff\",\"path\":\"sprites/asset_texture_cross_anime_2009_02/asset_texture_cross_anime_2009_02.yy\",},\"resourceVersion\":\"1.0\",\"name\":\"\",\"tags\":[],\"resourceType\":\"GMSpriteBitmap\",},",
		"-      ],\"parent\":{\"name\":\"asset_texture_cross_anime_2009_02\",\"path\":\"sprites/asset_texture_cross_anime_2009_02/asset_texture_cross_anime_2009_02.yy\",},\"resourceVersion\":\"1.0\",\"name\":\"dcf33cc9-92a5-41d4-a378-20e3d1e2c4d3\",\"tags\":[],\"resourceType\":\"GMSpriteFrame\",},",
		"+    {\"compositeImage\":{\"FrameId\":{\"name\":\"e55efbdd-2ee9-44ac-97c1-baa3d5679e8d\",\"path\":\"sprites/asset_texture_cross_anime_2009_02/asset_texture_cross_anime_2009_02.yy\",},\"LayerId\":null,\"resourceVersion\":\"1.0\",\"name\":\"\",\"tags\":[],\"resourceType\":\"GMSpriteBitmap\",},\"images\":[",
		"+        {\"FrameId\":{\"name\":\"e55efbdd-2ee9-44ac-97c1-baa3d5679e8d\",\"path\":\"sprites/asset_texture_cross_anime_2009_02/asset_texture_cross_anime_2009_02.yy\",},\"LayerId\":{\"name\":\"a8fed5b0-6ea8-419f-95cd-6cf7c43f1d47\",\"path\":\"sprites/asset_texture_cross_anime_2009_02/asset_texture_cross_anime_2009_02.yy\",},\"resourceVersion\":\"1.0\",\"name\":\"\",\"tags\":[],\"resourceType\":\"GMSpriteBitmap\",},",
		"+      ],\"parent\":{\"name\":\"asset_texture_cross_anime_2009_02\",\"path\":\"sprites/asset_texture_cross_anime_2009_02/asset_texture_cross_anime_2009_02.yy\",},\"resourceVersion\":\"1.0\",\"name\":\"e55efbdd-2ee9-44ac-97c1-baa3d5679e8d\",\"tags\":[],\"resourceType\":\"GMSpriteFrame\",},",
		"   ],",
		"   \"sequence\": {",
		"     \"spriteId\": {\"name\":\"asset_texture_cross_anime_2009_02\",\"path\":\"sprites/asset_texture_cross_anime_2009_02/asset_texture_cross_anime_2009_02.yy\",},",
		"@@ -41,7 +41,7 @@",
		"     \"moments\": {\"Keyframes\":[],\"resourceVersion\":\"1.0\",\"resourceType\":\"KeyframeStore<MomentsEventKeyframe>\",},",
		"     \"tracks\": [",
		"       {\"name\":\"frames\",\"spriteId\":null,\"keyframes\":{\"Keyframes\":[",
		"-            {\"id\":\"af30aaaa-1113-4734-ae34-96267ce27895\",\"Key\":0.0,\"Length\":1.0,\"Stretch\":false,\"Disabled\":false,\"IsCreationKey\":false,\"Channels\":{\"0\":{\"Id\":{\"name\":\"dcf33cc9-92a5-41d4-a378-20e3d1e2c4d3\",\"path\":\"sprites/asset_texture_cross_anime_2009_02/asset_texture_cross_anime_2009_02.yy\",},\"resourceVersion\":\"1.0\",\"resourceType\":\"SpriteFrameKeyframe\",},},\"resourceVersion\":\"1.0\",\"resourceType\":\"Keyframe<SpriteFrameKeyframe>\",},",
		"+            {\"id\":\"8785a32f-9bbf-490e-b7a2-8ac5a0f5a72d\",\"Key\":0.0,\"Length\":1.0,\"Stretch\":false,\"Disabled\":false,\"IsCreationKey\":false,\"Channels\":{\"0\":{\"Id\":{\"name\":\"e55efbdd-2ee9-44ac-97c1-baa3d5679e8d\",\"path\":\"sprites/asset_texture_cross_anime_2009_02/asset_texture_cross_anime_2009_02.yy\",},\"resourceVersion\":\"1.0\",\"resourceType\":\"SpriteFrameKeyframe\",},},\"resourceVersion\":\"1.0\",\"resourceType\":\"Keyframe<SpriteFrameKeyframe>\",},",
		"           ],\"resourceVersion\":\"1.0\",\"resourceType\":\"KeyframeStore<SpriteFrameKeyframe>\",},\"trackColour\":0,\"inheritsTrackColour\":true,\"builtinName\":0,\"traits\":0,\"interpolation\":1,\"tracks\":[],\"events\":[],\"isCreationTrack\":false,\"resourceVersion\":\"1.0\",\"tags\":[],\"resourceType\":\"GMSpriteFramesTrack\",\"modifiers\":[],},",
		"     ],",
		"     \"visibleRange\": null,",
		"@@ -65,7 +65,7 @@",
		"     \"resourceType\": \"GMSequence\",",
		"   },",
		"   \"layers\": [",
		"-    {\"visible\":true,\"isLocked\":false,\"blendMode\":0,\"opacity\":100.0,\"displayName\":\"default\",\"resourceVersion\":\"1.0\",\"name\":\"9030ecf9-8184-4ef1-a6b1-186a1ffcf5ff\",\"tags\":[],\"resourceType\":\"GMImageLayer\",},",
		"+    {\"visible\":true,\"isLocked\":false,\"blendMode\":0,\"opacity\":100.0,\"displayName\":\"default\",\"resourceVersion\":\"1.0\",\"name\":\"a8fed5b0-6ea8-419f-95cd-6cf7c43f1d47\",\"tags\":[],\"resourceType\":\"GMImageLayer\",},",
		"   ],",
		"   \"nineSlice\": null,",
		"   \"parent\": {",
		"diff --git a/yyp/sprites/asset_texture_cross_anime_2009_02/dcf33cc9-92a5-41d4-a378-20e3d1e2c4d3.png b/yyp/sprites/asset_texture_cross_anime_2009_02/dcf33cc9-92a5-41d4-a378-20e3d1e2c4d3.png",
		"deleted file mode 100644",
		"index db25af8..0000000",
		"Binary files a/yyp/sprites/asset_texture_cross_anime_2009_02/dcf33cc9-92a5-41d4-a378-20e3d1e2c4d3.png and /dev/null differ",
		"diff --git a/yyp/sprites/asset_texture_cross_anime_2009_02/layers/dcf33cc9-92a5-41d4-a378-20e3d1e2c4d3/9030ecf9-8184-4ef1-a6b1-186a1ffcf5ff.png b/yyp/sprites/asset_texture_cross_anime_2009_02/layers/dcf33cc9-92a5-41d4-a378-20e3d1e2c4d3/9030ecf9-8184-4ef1-a6b1-186a1ffcf5ff.png",
		"deleted file mode 100644",
		"index db25af8..0000000",
		"Binary files a/yyp/sprites/asset_texture_cross_anime_2009_02/layers/dcf33cc9-92a5-41d4-a378-20e3d1e2c4d3/9030ecf9-8184-4ef1-a6b1-186a1ffcf5ff.png and /dev/null differ",
		"diff --git a/yyp/sprites/asset_texture_cross_anime_2009_03/50603404-b3d9-48ec-bf11-dd25bad1d60a.png b/yyp/sprites/asset_texture_cross_anime_2009_03/50603404-b3d9-48ec-bf11-dd25bad1d60a.png",
		"deleted file mode 100644",
		"index 21f9523..0000000",
		"Binary files a/yyp/sprites/asset_texture_cross_anime_2009_03/50603404-b3d9-48ec-bf11-dd25bad1d60a.png and /dev/null differ",
		"diff --git a/yyp/sprites/asset_texture_cross_anime_2009_03/asset_texture_cross_anime_2009_03.yy b/yyp/sprites/asset_texture_cross_anime_2009_03/asset_texture_cross_anime_2009_03.yy",
		"index 4602d2d..e930d89 100644",
		"--- a/yyp/sprites/asset_texture_cross_anime_2009_03/asset_texture_cross_anime_2009_03.yy",
		"+++ b/yyp/sprites/asset_texture_cross_anime_2009_03/asset_texture_cross_anime_2009_03.yy",
		"@@ -8,14 +8,14 @@",
		"   \"collisionTolerance\": 0,",
		"   \"swfPrecision\": 2.525,",
		"   \"bbox_left\": 0,",
		"-  \"bbox_right\": 604,",
		"+  \"bbox_right\": 2701,",
		"   \"bbox_top\": 0,",
		"-  \"bbox_bottom\": 767,",
		"+  \"bbox_bottom\": 1213,",
		"   \"HTile\": false,",
		"   \"VTile\": false,",
		"   \"For3D\": false,",
		"-  \"width\": 605,",
		"-  \"height\": 768,",
		"+  \"width\": 2702,",
		"+  \"height\": 1214,",
		"   \"textureGroupId\": {",
		"     \"name\": \"Default\",",
		"     \"path\": \"texturegroups/Default\",",
		"@@ -24,9 +24,9 @@",
		"   \"gridX\": 0,",
		"   \"gridY\": 0,",
		"   \"frames\": [",
		"-    {\"compositeImage\":{\"FrameId\":{\"name\":\"50603404-b3d9-48ec-bf11-dd25bad1d60a\",\"path\":\"sprites/asset_texture_cross_anime_2009_03/asset_texture_cross_anime_2009_03.yy\",},\"LayerId\":null,\"resourceVersion\":\"1.0\",\"name\":\"\",\"tags\":[],\"resourceType\":\"GMSpriteBitmap\",},\"images\":[",
		"-        {\"FrameId\":{\"name\":\"50603404-b3d9-48ec-bf11-dd25bad1d60a\",\"path\":\"sprites/asset_texture_cross_anime_2009_03/asset_texture_cross_anime_2009_03.yy\",},\"LayerId\":{\"name\":\"945ef1be-27cf-48a4-ab4a-e50a2e00e47e\",\"path\":\"sprites/asset_texture_cross_anime_2009_03/asset_texture_cross_anime_2009_03.yy\",},\"resourceVersion\":\"1.0\",\"name\":\"\",\"tags\":[],\"resourceType\":\"GMSpriteBitmap\",},",
		"-      ],\"parent\":{\"name\":\"asset_texture_cross_anime_2009_03\",\"path\":\"sprites/asset_texture_cross_anime_2009_03/asset_texture_cross_anime_2009_03.yy\",},\"resourceVersion\":\"1.0\",\"name\":\"50603404-b3d9-48ec-bf11-dd25bad1d60a\",\"tags\":[],\"resourceType\":\"GMSpriteFrame\",},",
		"+    {\"compositeImage\":{\"FrameId\":{\"name\":\"1324b6e0-02ab-4bd0-b0d8-f75f97d3f1e0\",\"path\":\"sprites/asset_texture_cross_anime_2009_03/asset_texture_cross_anime_2009_03.yy\",},\"LayerId\":null,\"resourceVersion\":\"1.0\",\"name\":\"\",\"tags\":[],\"resourceType\":\"GMSpriteBitmap\",},\"images\":[",
		"+        {\"FrameId\":{\"name\":\"1324b6e0-02ab-4bd0-b0d8-f75f97d3f1e0\",\"path\":\"sprites/asset_texture_cross_anime_2009_03/asset_texture_cross_anime_2009_03.yy\",},\"LayerId\":{\"name\":\"1d086b06-1089-4948-ba4a-770be5a6a15a\",\"path\":\"sprites/asset_texture_cross_anime_2009_03/asset_texture_cross_anime_2009_03.yy\",},\"resourceVersion\":\"1.0\",\"name\":\"\",\"tags\":[],\"resourceType\":\"GMSpriteBitmap\",},",
		"+      ],\"parent\":{\"name\":\"asset_texture_cross_anime_2009_03\",\"path\":\"sprites/asset_texture_cross_anime_2009_03/asset_texture_cross_anime_2009_03.yy\",},\"resourceVersion\":\"1.0\",\"name\":\"1324b6e0-02ab-4bd0-b0d8-f75f97d3f1e0\",\"tags\":[],\"resourceType\":\"GMSpriteFrame\",},",
		"   ],",
		"   \"sequence\": {",
		"     \"spriteId\": {\"name\":\"asset_texture_cross_anime_2009_03\",\"path\":\"sprites/asset_texture_cross_anime_2009_03/asset_texture_cross_anime_2009_03.yy\",},",
		"@@ -41,7 +41,7 @@",
		"     \"moments\": {\"Keyframes\":[],\"resourceVersion\":\"1.0\",\"resourceType\":\"KeyframeStore<MomentsEventKeyframe>\",},",
		"     \"tracks\": [",
		"       {\"name\":\"frames\",\"spriteId\":null,\"keyframes\":{\"Keyframes\":[",
		"-            {\"id\":\"c601f341-9cd0-438e-8d79-27deb9a2e7bc\",\"Key\":0.0,\"Length\":1.0,\"Stretch\":false,\"Disabled\":false,\"IsCreationKey\":false,\"Channels\":{\"0\":{\"Id\":{\"name\":\"50603404-b3d9-48ec-bf11-dd25bad1d60a\",\"path\":\"sprites/asset_texture_cross_anime_2009_03/asset_texture_cross_anime_2009_03.yy\",},\"resourceVersion\":\"1.0\",\"resourceType\":\"SpriteFrameKeyframe\",},},\"resourceVersion\":\"1.0\",\"resourceType\":\"Keyframe<SpriteFrameKeyframe>\",},",
		"+            {\"id\":\"9e05c1e3-f7c5-42c5-aaec-d09b7b2f3147\",\"Key\":0.0,\"Length\":1.0,\"Stretch\":false,\"Disabled\":false,\"IsCreationKey\":false,\"Channels\":{\"0\":{\"Id\":{\"name\":\"1324b6e0-02ab-4bd0-b0d8-f75f97d3f1e0\",\"path\":\"sprites/asset_texture_cross_anime_2009_03/asset_texture_cross_anime_2009_03.yy\",},\"resourceVersion\":\"1.0\",\"resourceType\":\"SpriteFrameKeyframe\",},},\"resourceVersion\":\"1.0\",\"resourceType\":\"Keyframe<SpriteFrameKeyframe>\",},",
		"           ],\"resourceVersion\":\"1.0\",\"resourceType\":\"KeyframeStore<SpriteFrameKeyframe>\",},\"trackColour\":0,\"inheritsTrackColour\":true,\"builtinName\":0,\"traits\":0,\"interpolation\":1,\"tracks\":[],\"events\":[],\"isCreationTrack\":false,\"resourceVersion\":\"1.0\",\"tags\":[],\"resourceType\":\"GMSpriteFramesTrack\",\"modifiers\":[],},",
		"     ],",
		"     \"visibleRange\": null,",
		"@@ -65,7 +65,7 @@",
		"     \"resourceType\": \"GMSequence\",",
		"   },",
		"   \"layers\": [",
		"-    {\"visible\":true,\"isLocked\":false,\"blendMode\":0,\"opacity\":100.0,\"displayName\":\"default\",\"resourceVersion\":\"1.0\",\"name\":\"945ef1be-27cf-48a4-ab4a-e50a2e00e47e\",\"tags\":[],\"resourceType\":\"GMImageLayer\",},",
		"+    {\"visible\":true,\"isLocked\":false,\"blendMode\":0,\"opacity\":100.0,\"displayName\":\"default\",\"resourceVersion\":\"1.0\",\"name\":\"1d086b06-1089-4948-ba4a-770be5a6a15a\",\"tags\":[],\"resourceType\":\"GMImageLayer\",},",
		"   ],",
		"   \"nineSlice\": null,",
		"   \"parent\": {",
		"diff --git a/yyp/sprites/asset_texture_cross_anime_2009_03/layers/50603404-b3d9-48ec-bf11-dd25bad1d60a/945ef1be-27cf-48a4-ab4a-e50a2e00e47e.png b/yyp/sprites/asset_texture_cross_anime_2009_03/layers/50603404-b3d9-48ec-bf11-dd25bad1d60a/945ef1be-27cf-48a4-ab4a-e50a2e00e47e.png",
		"deleted file mode 100644",
		"index 21f9523..0000000",
		"Binary files a/yyp/sprites/asset_texture_cross_anime_2009_03/layers/50603404-b3d9-48ec-bf11-dd25bad1d60a/945ef1be-27cf-48a4-ab4a-e50a2e00e47e.png and /dev/null differ",
		"diff --git a/yyp/sprites/asset_texture_cross_anime_2009_04/8e57d853-5a9f-4ed5-b427-c958ae73c212.png b/yyp/sprites/asset_texture_cross_anime_2009_04/8e57d853-5a9f-4ed5-b427-c958ae73c212.png",
		"deleted file mode 100644",
		"index d66a004..0000000",
		"Binary files a/yyp/sprites/asset_texture_cross_anime_2009_04/8e57d853-5a9f-4ed5-b427-c958ae73c212.png and /dev/null differ",
		"diff --git a/yyp/sprites/asset_texture_cross_anime_2009_04/asset_texture_cross_anime_2009_04.yy b/yyp/sprites/asset_texture_cross_anime_2009_04/asset_texture_cross_anime_2009_04.yy",
		"index 0ac2e1e..770066f 100644",
		"--- a/yyp/sprites/asset_texture_cross_anime_2009_04/asset_texture_cross_anime_2009_04.yy",
		"+++ b/yyp/sprites/asset_texture_cross_anime_2009_04/asset_texture_cross_anime_2009_04.yy",
		"@@ -8,14 +8,14 @@",
		"   \"collisionTolerance\": 0,",
		"   \"swfPrecision\": 2.525,",
		"   \"bbox_left\": 0,",
		"-  \"bbox_right\": 499,",
		"-  \"bbox_top\": 16,",
		"-  \"bbox_bottom\": 499,",
		"+  \"bbox_right\": 2421,",
		"+  \"bbox_top\": 0,",
		"+  \"bbox_bottom\": 1499,",
		"   \"HTile\": false,",
		"   \"VTile\": false,",
		"   \"For3D\": false,",
		"-  \"width\": 500,",
		"-  \"height\": 500,",
		"+  \"width\": 2422,",
		"+  \"height\": 1500,",
		"   \"textureGroupId\": {",
		"     \"name\": \"Default\",",
		"     \"path\": \"texturegroups/Default\",",
		"@@ -24,9 +24,9 @@",
		"   \"gridX\": 0,",
		"   \"gridY\": 0,",
		"   \"frames\": [",
		"-    {\"compositeImage\":{\"FrameId\":{\"name\":\"8e57d853-5a9f-4ed5-b427-c958ae73c212\",\"path\":\"sprites/asset_texture_cross_anime_2009_04/asset_texture_cross_anime_2009_04.yy\",},\"LayerId\":null,\"resourceVersion\":\"1.0\",\"name\":\"\",\"tags\":[],\"resourceType\":\"GMSpriteBitmap\",},\"images\":[",
		"-        {\"FrameId\":{\"name\":\"8e57d853-5a9f-4ed5-b427-c958ae73c212\",\"path\":\"sprites/asset_texture_cross_anime_2009_04/asset_texture_cross_anime_2009_04.yy\",},\"LayerId\":{\"name\":\"054c407f-44a4-44e4-b2e1-2578ec07e41f\",\"path\":\"sprites/asset_texture_cross_anime_2009_04/asset_texture_cross_anime_2009_04.yy\",},\"resourceVersion\":\"1.0\",\"name\":\"\",\"tags\":[],\"resourceType\":\"GMSpriteBitmap\",},",
		"-      ],\"parent\":{\"name\":\"asset_texture_cross_anime_2009_04\",\"path\":\"sprites/asset_texture_cross_anime_2009_04/asset_texture_cross_anime_2009_04.yy\",},\"resourceVersion\":\"1.0\",\"name\":\"8e57d853-5a9f-4ed5-b427-c958ae73c212\",\"tags\":[],\"resourceType\":\"GMSpriteFrame\",},",
		"+    {\"compositeImage\":{\"FrameId\":{\"name\":\"629e3454-9c4e-4365-884c-5de9dfc9f094\",\"path\":\"sprites/asset_texture_cross_anime_2009_04/asset_texture_cross_anime_2009_04.yy\",},\"LayerId\":null,\"resourceVersion\":\"1.0\",\"name\":\"\",\"tags\":[],\"resourceType\":\"GMSpriteBitmap\",},\"images\":[",
		"+        {\"FrameId\":{\"name\":\"629e3454-9c4e-4365-884c-5de9dfc9f094\",\"path\":\"sprites/asset_texture_cross_anime_2009_04/asset_texture_cross_anime_2009_04.yy\",},\"LayerId\":{\"name\":\"6ca77b03-0246-4c7b-b1ad-5c2e6b89e689\",\"path\":\"sprites/asset_texture_cross_anime_2009_04/asset_texture_cross_anime_2009_04.yy\",},\"resourceVersion\":\"1.0\",\"name\":\"\",\"tags\":[],\"resourceType\":\"GMSpriteBitmap\",},",
		"+      ],\"parent\":{\"name\":\"asset_texture_cross_anime_2009_04\",\"path\":\"sprites/asset_texture_cross_anime_2009_04/asset_texture_cross_anime_2009_04.yy\",},\"resourceVersion\":\"1.0\",\"name\":\"629e3454-9c4e-4365-884c-5de9dfc9f094\",\"tags\":[],\"resourceType\":\"GMSpriteFrame\",},",
		"   ],",
		"   \"sequence\": {",
		"     \"spriteId\": {\"name\":\"asset_texture_cross_anime_2009_04\",\"path\":\"sprites/asset_texture_cross_anime_2009_04/asset_texture_cross_anime_2009_04.yy\",},",
		"@@ -41,7 +41,7 @@",
		"     \"moments\": {\"Keyframes\":[],\"resourceVersion\":\"1.0\",\"resourceType\":\"KeyframeStore<MomentsEventKeyframe>\",},",
		"     \"tracks\": [",
		"       {\"name\":\"frames\",\"spriteId\":null,\"keyframes\":{\"Keyframes\":[",
		"-            {\"id\":\"634a0b49-a580-4187-8596-759c7d233963\",\"Key\":0.0,\"Length\":1.0,\"Stretch\":false,\"Disabled\":false,\"IsCreationKey\":false,\"Channels\":{\"0\":{\"Id\":{\"name\":\"8e57d853-5a9f-4ed5-b427-c958ae73c212\",\"path\":\"sprites/asset_texture_cross_anime_2009_04/asset_texture_cross_anime_2009_04.yy\",},\"resourceVersion\":\"1.0\",\"resourceType\":\"SpriteFrameKeyframe\",},},\"resourceVersion\":\"1.0\",\"resourceType\":\"Keyframe<SpriteFrameKeyframe>\",},",
		"+            {\"id\":\"acd16eed-8bef-4634-aee0-4e192b7397e8\",\"Key\":0.0,\"Length\":1.0,\"Stretch\":false,\"Disabled\":false,\"IsCreationKey\":false,\"Channels\":{\"0\":{\"Id\":{\"name\":\"629e3454-9c4e-4365-884c-5de9dfc9f094\",\"path\":\"sprites/asset_texture_cross_anime_2009_04/asset_texture_cross_anime_2009_04.yy\",},\"resourceVersion\":\"1.0\",\"resourceType\":\"SpriteFrameKeyframe\",},},\"resourceVersion\":\"1.0\",\"resourceType\":\"Keyframe<SpriteFrameKeyframe>\",},",
		"           ],\"resourceVersion\":\"1.0\",\"resourceType\":\"KeyframeStore<SpriteFrameKeyframe>\",},\"trackColour\":0,\"inheritsTrackColour\":true,\"builtinName\":0,\"traits\":0,\"interpolation\":1,\"tracks\":[],\"events\":[],\"isCreationTrack\":false,\"resourceVersion\":\"1.0\",\"tags\":[],\"resourceType\":\"GMSpriteFramesTrack\",\"modifiers\":[],},",
		"     ],",
		"     \"visibleRange\": null,",
		"@@ -65,7 +65,7 @@",
		"     \"resourceType\": \"GMSequence\",",
		"   },",
		"   \"layers\": [",
		"-    {\"visible\":true,\"isLocked\":false,\"blendMode\":0,\"opacity\":100.0,\"displayName\":\"default\",\"resourceVersion\":\"1.0\",\"name\":\"054c407f-44a4-44e4-b2e1-2578ec07e41f\",\"tags\":[],\"resourceType\":\"GMImageLayer\",},",
		"+    {\"visible\":true,\"isLocked\":false,\"blendMode\":0,\"opacity\":100.0,\"displayName\":\"default\",\"resourceVersion\":\"1.0\",\"name\":\"6ca77b03-0246-4c7b-b1ad-5c2e6b89e689\",\"tags\":[],\"resourceType\":\"GMImageLayer\",},",
		"   ],",
		"   \"nineSlice\": null,",
		"   \"parent\": {",
		"diff --git a/yyp/sprites/asset_texture_cross_anime_2009_04/layers/8e57d853-5a9f-4ed5-b427-c958ae73c212/054c407f-44a4-44e4-b2e1-2578ec07e41f.png b/yyp/sprites/asset_texture_cross_anime_2009_04/layers/8e57d853-5a9f-4ed5-b427-c958ae73c212/054c407f-44a4-44e4-b2e1-2578ec07e41f.png",
		"deleted file mode 100644",
		"index d66a004..0000000",
		"Binary files a/yyp/sprites/asset_texture_cross_anime_2009_04/layers/8e57d853-5a9f-4ed5-b427-c958ae73c212/054c407f-44a4-44e4-b2e1-2578ec07e41f.png and /dev/null differ",
		"",
		"",
		"",
		"",
		"ATTENTION CITIZEN! 市民请注意!",
		"流れてく 時の中ででも",
		"気だるさが ほらグルグル廻って",
		"私から 離れる心も",
		"見えないわ そう知らない？",
		"自分から 動くこともなく",
		"時の隙間に 流され続けて",
		"知らないわ 周りのことなど",
		"私は私 それだけ",
		"夢見てる？ なにも見てない？",
		"語るも無駄な 自分の言葉？",
		"悲しむなんて 疲れるだけよ",
		"何も感じず 過ごせばいいの",
		"戸惑う言葉 与えられても",
		"自分の心 ただ上の空",
		"もし私から 動くのならば",
		"すべて変えるのなら 黒にする",
		"こんな自分に 未来はあるの？",
		"こんな世界に 私はいるの？",
		"今切ないの？ 今悲しいの？",
		"自分の事も わからないまま",
		"歩むことさえ 疲れるだけよ",
		"人のことなど 知りもしないわ",
		"こんな私も 変われるのなら",
		"もし変われるのなら 白になる？",
		"流れてく 時の中ででも",
		"気だるさが ほらグルグル廻って",
		"私から 離れる心も",
		"見えないわ そう知らない？",
		"自分から 動くこともなく",
		"時の隙間に 流され続けて",
		"知らないわ 周りのことなど",
		"私は私 それだけ",
		"夢見てる？ なにも見てない？",
		"語るも無駄な 自分の言葉？",
		"悲しむなんて 疲れるだけよ",
		"何も感じず 過ごせばいいの",
		"戸惑う言葉 与えられても",
		"自分の心 ただ上の空",
		"もし私から 動くのならば",
		"すべて変えるのなら 黒にする",
		"無駄な時間に 未来はあるの？",
		"こんな所に 私は居るの？",
		"私のことを 言いたいならば",
		"言葉にするのなら「ろくでなし」",
		"こんな所に 私はいるの？",
		"こんな時間に 私はいるの？",
		"こんな私も 変われるのなら",
		"もし変われるのなら 白になる？",
		"今夢見てる？ なにも見てない？",
		"語るも無駄な 自分の言葉？",
		"悲しむなんて 疲れるだけよ",
		"何も感じず 過ごせばいいの",
		"戸惑う言葉 与えられても",
		"自分の心 ただ上の空",
		"もし私から 動くのならば",
		"すべて変えるのなら 黒にする",
		"動くのならば 動くのならば",
		"すべて壊すわ すべて壊すわ",
		"悲しむならば 悲しむならば",
		"私の心 白く変われる？",
		"貴方の事も 私のことも",
		"全ての事も まだ知らないの",
		"重い目蓋を 開けたのならば",
		"すべて壊すのなら 黒になれ",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"   And you don't seem to understand",
		"  A shame you seemed an honest man",
		"      And all the fears you hold so dear",
		"   Will turn to whisper in your ear",
		"        And you know what they say might hurt you",
		"        And you know that it means so much",
		"   And you don't even feel a thing",
		"",
		"",
		"       I am falling, I am fading",
		"    I have lost it all",
		"",
		"      And you don't seem the lying kind",
		"      A shame that I can read your mind",
		"      And all the things that I read there",
		"     Candle-lit smile that we both share",
		"      And you know I don't mean to hurt you",
		"  But you know that it means so much",
		"      And you don't even feel a thing",
		"",
		"I am falling, I am fading, I am drowning",
		"Help me to breathe",
		"I am hurting, I have lost it all",
		"I am losing",
		"Help me to breathe",
		"S E W E R C O R E S E W E R C O R E ",
		"S E W E R C O R E S E W E R C O R E ",
		"S E W E R C こ ん E S E W 変 R C O R E",
		"S E W え R C O R て S E え E R C O R E",
		"00:00 Nowhere To Run",
		"[System]: >_ Midbooze - Nowhere To run",
		"M   indbooze",
		"    空M     M  i      M   indbooze",
		"           M     M     M   indbooze",
		"    06:47 Vague Sense",
		"    てi     i   d      i ",
		"            i     i     i",
		"         もし私から 動くのならば",
		"            22:03 Spiritbite",
		"S E W E R C O R E S E W E R C O R E",
		"        d         d    b  ",
		"                d            d ",
		"            d         d booze",
		"            b             b   ",
		"S E W E R C O R E S E W E R C O R E",
		"      17:43 Labyrinth",
		" 22:03 Spiritbite           o              ",
		"    b                b           ",
		"          o           o     ",
		"          黒にする",
		"            o            o     ",
		"         o           o           o",
		"            o             o   ",
		"",
		"                 z             ",
		"         o                o    ",
		"          z           z ",
		"          全ての事も    ",
		"          17:43 Labyrinth",
		"               22:03 Spiritbite",
		"           25:51 Helplessness",
		"             31:07 Bad Ending",
		"              e            z   ",
		"               z           z      ",
		"S E W E R C O R E S E W E R C O R E",
		"S E W E R C O R E S E W E R C O R E    ",
		"          e           e     ",
		"",
		"                 e             ",
		"         e           e         e",
		"    M",
		"    i",
		"        d",
		"            b",
		"          o",
		"            o",
		"          z",
		"          e",
		"S E W E R C O R E S E W E R C O R E",
		"S E W E R C O R E S E W E R C O R E ",
		"S E W E R C O R E S E W E R C O R E ",
		"S E W E R C こ ん E S E W 変 R C O R E",
		"S E W え R C O R て S E え E R C O R E",
		"00:00 Nowhere To Run",
		"[System]: >_ Midbooze - Nowhere To run",
		"M   indbooze",
		"    空M     M  i      M   indbooze",
		"           M     M     M   indbooze",
		"    06:47 Vague Sense",
		"    てi     i   d      i ",
		"            i     i     i",
		"         もし私から 動くのならば",
		"            22:03 Spiritbite",
		"S E W E R C O R E S E W E R C O R E",
		"        d         d    b  ",
		"                d            d ",
		"            d         d booze",
		"            b             b   ",
		"S E W E R C O R E S E W E R C O R E",
		"      17:43 Labyrinth",
		" 22:03 Spiritbite           o              ",
		"    b                b           ",
		"          o           o     ",
		"          黒にする",
		"            o            o     ",
		"         o           o           o",
		"            o             o   ",
		"",
		"                 z             ",
		"         o                o    ",
		"          z           z ",
		"          全ての事も    ",
		"          17:43 Labyrinth",
		"               22:03 Spiritbite",
		"           25:51 Helplessness",
		"             31:07 Bad Ending",
		"              e            z   ",
		"               z           z      ",
		"S E W E R C O R E S E W E R C O R E",
		"S E W E R C O R E S E W E R C O R E    ",
		"          e           e     ",
		"",
		"                 e             ",
		"         e           e         e",
		"    M",
		"    i",
		"        d",
		"            b",
		"          o",
		"            o",
		"          z",
		"          e",
		"S E W E R C O R E S E W E R C O R E ",
		"S E W E R C O R E S E W E R C O R E ",
		"S E W E R C こ ん E S E W 変 R C O R E",
		"S E W え R C O R て S E え E R C O R E",
		"00:00 Nowhere To Run",
		"[System]: >_ Midbooze - Nowhere To run",
		"M   indbooze",
		"    空M     M  i      M   indbooze",
		"           M     M     M   indbooze",
		"    06:47 Vague Sense",
		"    てi     i   d      i ",
		"            i     i     i",
		"         もし私から 動くのならば",
		"            22:03 Spiritbite",
		"S E W E R C O R E S E W E R C O R E",
		"        d         d    b  ",
		"                d            d ",
		"            d         d booze",
		"            b             b   ",
		"S E W E R C O R E S E W E R C O R E",
		"      17:43 Labyrinth",
		" 22:03 Spiritbite           o              ",
		"    b                b           ",
		"          o           o     ",
		"          黒にする",
		"            o            o     ",
		"         o           o           o",
		"            o             o   ",
		"",
		"                 z             ",
		"         o                o    ",
		"          z           z ",
		"          全ての事も    ",
		"          17:43 Labyrinth",
		"               22:03 Spiritbite",
		"           25:51 Helplessness",
		"             31:07 Bad Ending",
		"              e            z   ",
		"               z           z      ",
		"S E W E R C O R E S E W E R C O R E",
		"S E W E R C O R E S E W E R C O R E    ",
		"          e           e     ",
		"",
		"                 e             ",
		"         e           e         e",
		"    M",
		"    i",
		"        d",
		"            b",
		"          o",
		"            o",
		"          z",
		"          e",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		"",
		""
	];
